package com.compomics.colims.client.view.admin.instrument;

import com.compomics.colims.client.compoment.DualList;
import com.compomics.colims.model.InstrumentCvParam;
import java.awt.Dialog;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author Niels Hulstaert
 */
public class InstrumentEditDialog extends javax.swing.JDialog {

    /**
     * Dialog constructor.
     *
     * @param parent the parent dialog
     * @param modal the modal boolean
     */
    public InstrumentEditDialog(final Dialog parent, final boolean modal) {
        super(parent, modal);

        initComponents();

        setLocationRelativeTo(parent);
    }

    public JButton getCancelInstrumentEditButton() {
        return cancelInstrumentEditButton;
    }

    public DualList<InstrumentCvParam> getCvParamDualList() {
        return cvParamDualList;
    }

    public JList getCvParamSummaryList() {
        return cvParamSummaryList;
    }

    public JButton getInstrumentCvParamsCrudButton() {
        return instrumentCvParamsCrudButton;
    }

    public JButton getInstrumentSaveOrUpdateButton() {
        return instrumentSaveOrUpdateButton;
    }

    public JTextField getNameTextField() {
        return nameTextField;
    }

    public JLabel getInstrumentStateInfoLabel() {
        return instrumentStateInfoLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instrumentEditPanel = new javax.swing.JPanel();
        instrumentStateInfoLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        cancelInstrumentEditButton = new javax.swing.JButton();
        instrumentSaveOrUpdateButton = new javax.swing.JButton();
        cvParamsPanel = new javax.swing.JPanel();
        cvParamSummaryScrollPane = new javax.swing.JScrollPane();
        cvParamSummaryList = new javax.swing.JList();
        cvParamDualList = new com.compomics.colims.client.compoment.DualList<>();
        instrumentCvParamsCrudButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instrument management");
        setPreferredSize(new java.awt.Dimension(720, 377));

        instrumentEditPanel.setBackground(new java.awt.Color(255, 255, 255));

        instrumentStateInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        instrumentStateInfoLabel.setForeground(new java.awt.Color(250, 0, 0));
        instrumentStateInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        instrumentStateInfoLabel.setMaximumSize(new java.awt.Dimension(0, 20));
        instrumentStateInfoLabel.setMinimumSize(new java.awt.Dimension(0, 20));
        instrumentStateInfoLabel.setPreferredSize(new java.awt.Dimension(0, 20));

        nameLabel.setText("Name*");

        cancelInstrumentEditButton.setText("cancel");
        cancelInstrumentEditButton.setMaximumSize(new java.awt.Dimension(80, 25));
        cancelInstrumentEditButton.setMinimumSize(new java.awt.Dimension(80, 25));
        cancelInstrumentEditButton.setPreferredSize(new java.awt.Dimension(80, 25));

        instrumentSaveOrUpdateButton.setText("save");
        instrumentSaveOrUpdateButton.setMaximumSize(new java.awt.Dimension(80, 25));
        instrumentSaveOrUpdateButton.setMinimumSize(new java.awt.Dimension(80, 25));
        instrumentSaveOrUpdateButton.setPreferredSize(new java.awt.Dimension(80, 25));

        cvParamsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("CV params"));
        cvParamsPanel.setOpaque(false);

        cvParamSummaryScrollPane.setViewportView(cvParamSummaryList);

        instrumentCvParamsCrudButton.setText("edit...");
        instrumentCvParamsCrudButton.setToolTipText("edit the available CV params of the selected CV param type");
        instrumentCvParamsCrudButton.setMaximumSize(new java.awt.Dimension(80, 25));
        instrumentCvParamsCrudButton.setMinimumSize(new java.awt.Dimension(80, 25));
        instrumentCvParamsCrudButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout cvParamsPanelLayout = new javax.swing.GroupLayout(cvParamsPanel);
        cvParamsPanel.setLayout(cvParamsPanelLayout);
        cvParamsPanelLayout.setHorizontalGroup(
            cvParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cvParamsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cvParamSummaryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cvParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instrumentCvParamsCrudButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvParamDualList, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                .addContainerGap())
        );
        cvParamsPanelLayout.setVerticalGroup(
            cvParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cvParamsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cvParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cvParamSummaryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(cvParamDualList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instrumentCvParamsCrudButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout instrumentEditPanelLayout = new javax.swing.GroupLayout(instrumentEditPanel);
        instrumentEditPanel.setLayout(instrumentEditPanelLayout);
        instrumentEditPanelLayout.setHorizontalGroup(
            instrumentEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cvParamsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instrumentEditPanelLayout.createSequentialGroup()
                        .addComponent(instrumentStateInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instrumentSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelInstrumentEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(instrumentEditPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTextField)))
                .addContainerGap())
        );
        instrumentEditPanelLayout.setVerticalGroup(
            instrumentEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(instrumentEditPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cvParamsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(instrumentEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelInstrumentEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instrumentSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instrumentStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(instrumentEditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(instrumentEditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelInstrumentEditButton;
    private com.compomics.colims.client.compoment.DualList<com.compomics.colims.model.InstrumentCvParam> cvParamDualList;
    private javax.swing.JList cvParamSummaryList;
    private javax.swing.JScrollPane cvParamSummaryScrollPane;
    private javax.swing.JPanel cvParamsPanel;
    private javax.swing.JButton instrumentCvParamsCrudButton;
    private javax.swing.JPanel instrumentEditPanel;
    private javax.swing.JButton instrumentSaveOrUpdateButton;
    private javax.swing.JLabel instrumentStateInfoLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables

}
