package com.compomics.colims.client.view.admin.instrument;

import java.awt.Dialog;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Niels Hulstaert
 */
public class InstrumentTypeManagementDialog extends javax.swing.JDialog {
    
    /**
     * Dialog constructor
     * 
     * @param parent the parent dialog
     * @param modal the modal boolean
     */
    public InstrumentTypeManagementDialog(final Dialog parent, final boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        setLocationRelativeTo(parent);
    }

    public JButton getAddInstrumentTypeButton() {
        return addInstrumentTypeButton;
    }

    public JButton getDeleteInstrumentTypeButton() {
        return deleteInstrumentTypeButton;
    }

    public JTextArea getInstrumentTypeDescriptionTextArea() {
        return instrumentTypeDescriptionTextArea;
    }

    public JList getInstrumentTypeList() {
        return instrumentTypeList;
    }

    public JTextField getInstrumentTypeNameTextField() {
        return instrumentTypeNameTextField;
    }

    public JButton getInstrumentTypeSaveOrUpdateButton() {
        return instrumentTypeSaveOrUpdateButton;
    }

    public JLabel getInstrumentTypeStateInfoLabel() {
        return instrumentTypeStateInfoLabel;
    }        

    public JButton getCancelInstrumentTypeManagmentButton() {
        return cancelInstrumentTypeMangementButton;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instrumentTypeManagmentPanel = new javax.swing.JPanel();
        instrumentTypeOverviewPanel = new javax.swing.JPanel();
        instrumentTypeListScrollPane = new javax.swing.JScrollPane();
        instrumentTypeList = new javax.swing.JList();
        addInstrumentTypeButton = new javax.swing.JButton();
        deleteInstrumentTypeButton = new javax.swing.JButton();
        instrumentTypeDetailPanel = new javax.swing.JPanel();
        instrumentTypeDescriptionLabel = new javax.swing.JLabel();
        instrumentTypeNameLabel = new javax.swing.JLabel();
        instrumentTypeNameTextField = new javax.swing.JTextField();
        instrumentTypeSaveOrUpdateButton = new javax.swing.JButton();
        instrumentTypeStateInfoLabel = new javax.swing.JLabel();
        instrumentTypeDescriptionScrollPane = new javax.swing.JScrollPane();
        instrumentTypeDescriptionTextArea = new javax.swing.JTextArea();
        cancelInstrumentTypeMangementButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instrument type management");

        instrumentTypeManagmentPanel.setBackground(new java.awt.Color(255, 255, 255));

        instrumentTypeOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Overview"));
        instrumentTypeOverviewPanel.setOpaque(false);
        instrumentTypeOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        instrumentTypeListScrollPane.setOpaque(false);

        instrumentTypeListScrollPane.setViewportView(instrumentTypeList);

        addInstrumentTypeButton.setText("add");
        addInstrumentTypeButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addInstrumentTypeButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addInstrumentTypeButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deleteInstrumentTypeButton.setText("delete");
        deleteInstrumentTypeButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteInstrumentTypeButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteInstrumentTypeButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout instrumentTypeOverviewPanelLayout = new javax.swing.GroupLayout(instrumentTypeOverviewPanel);
        instrumentTypeOverviewPanel.setLayout(instrumentTypeOverviewPanelLayout);
        instrumentTypeOverviewPanelLayout.setHorizontalGroup(
            instrumentTypeOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentTypeOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrumentTypeListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(instrumentTypeOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteInstrumentTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addInstrumentTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        instrumentTypeOverviewPanelLayout.setVerticalGroup(
            instrumentTypeOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentTypeOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentTypeOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(instrumentTypeOverviewPanelLayout.createSequentialGroup()
                        .addComponent(addInstrumentTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteInstrumentTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(instrumentTypeListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addContainerGap())
        );

        instrumentTypeDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));
        instrumentTypeDetailPanel.setOpaque(false);
        instrumentTypeDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        instrumentTypeDescriptionLabel.setText("Description");

        instrumentTypeNameLabel.setText("Name*");
        instrumentTypeNameLabel.setPreferredSize(new java.awt.Dimension(48, 14));

        instrumentTypeSaveOrUpdateButton.setText("save");
        instrumentTypeSaveOrUpdateButton.setMaximumSize(new java.awt.Dimension(80, 25));
        instrumentTypeSaveOrUpdateButton.setMinimumSize(new java.awt.Dimension(80, 25));
        instrumentTypeSaveOrUpdateButton.setPreferredSize(new java.awt.Dimension(80, 25));

        instrumentTypeStateInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        instrumentTypeStateInfoLabel.setForeground(new java.awt.Color(255, 0, 0));
        instrumentTypeStateInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        instrumentTypeStateInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        instrumentTypeStateInfoLabel.setMaximumSize(new java.awt.Dimension(100, 20));
        instrumentTypeStateInfoLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        instrumentTypeStateInfoLabel.setPreferredSize(new java.awt.Dimension(100, 20));

        instrumentTypeDescriptionTextArea.setColumns(20);
        instrumentTypeDescriptionTextArea.setLineWrap(true);
        instrumentTypeDescriptionTextArea.setRows(5);
        instrumentTypeDescriptionScrollPane.setViewportView(instrumentTypeDescriptionTextArea);

        javax.swing.GroupLayout instrumentTypeDetailPanelLayout = new javax.swing.GroupLayout(instrumentTypeDetailPanel);
        instrumentTypeDetailPanel.setLayout(instrumentTypeDetailPanelLayout);
        instrumentTypeDetailPanelLayout.setHorizontalGroup(
            instrumentTypeDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentTypeDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentTypeDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instrumentTypeDetailPanelLayout.createSequentialGroup()
                        .addComponent(instrumentTypeStateInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instrumentTypeSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(instrumentTypeDetailPanelLayout.createSequentialGroup()
                        .addGroup(instrumentTypeDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(instrumentTypeDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(instrumentTypeNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(instrumentTypeDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instrumentTypeDescriptionScrollPane)
                            .addComponent(instrumentTypeNameTextField))))
                .addContainerGap())
        );
        instrumentTypeDetailPanelLayout.setVerticalGroup(
            instrumentTypeDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentTypeDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentTypeDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrumentTypeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instrumentTypeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(instrumentTypeDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(instrumentTypeDetailPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(instrumentTypeDescriptionLabel))
                    .addGroup(instrumentTypeDetailPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(instrumentTypeDescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(instrumentTypeDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instrumentTypeSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instrumentTypeStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cancelInstrumentTypeMangementButton.setText("cancel");
        cancelInstrumentTypeMangementButton.setMaximumSize(new java.awt.Dimension(80, 25));
        cancelInstrumentTypeMangementButton.setMinimumSize(new java.awt.Dimension(80, 25));
        cancelInstrumentTypeMangementButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout instrumentTypeManagmentPanelLayout = new javax.swing.GroupLayout(instrumentTypeManagmentPanel);
        instrumentTypeManagmentPanel.setLayout(instrumentTypeManagmentPanelLayout);
        instrumentTypeManagmentPanelLayout.setHorizontalGroup(
            instrumentTypeManagmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instrumentTypeManagmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentTypeManagmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(instrumentTypeDetailPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addComponent(instrumentTypeOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addComponent(cancelInstrumentTypeMangementButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        instrumentTypeManagmentPanelLayout.setVerticalGroup(
            instrumentTypeManagmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instrumentTypeManagmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrumentTypeOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instrumentTypeDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelInstrumentTypeMangementButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(instrumentTypeManagmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(instrumentTypeManagmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInstrumentTypeButton;
    private javax.swing.JButton cancelInstrumentTypeMangementButton;
    private javax.swing.JButton deleteInstrumentTypeButton;
    private javax.swing.JLabel instrumentTypeDescriptionLabel;
    private javax.swing.JScrollPane instrumentTypeDescriptionScrollPane;
    private javax.swing.JTextArea instrumentTypeDescriptionTextArea;
    private javax.swing.JPanel instrumentTypeDetailPanel;
    private javax.swing.JList instrumentTypeList;
    private javax.swing.JScrollPane instrumentTypeListScrollPane;
    private javax.swing.JPanel instrumentTypeManagmentPanel;
    private javax.swing.JLabel instrumentTypeNameLabel;
    private javax.swing.JTextField instrumentTypeNameTextField;
    private javax.swing.JPanel instrumentTypeOverviewPanel;
    private javax.swing.JButton instrumentTypeSaveOrUpdateButton;
    private javax.swing.JLabel instrumentTypeStateInfoLabel;
    // End of variables declaration//GEN-END:variables
    
}
