package com.compomics.colims.client.view.admin.instrument;

import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTable;

/**
 *
 * @author Niels Hulstaert
 */
public class InstrumentManagementDialog extends javax.swing.JDialog {
    
     /**
     * Dialog constructor
     * 
     * @param parent the parent frame
     * @param modal the modal boolean
     */
    public InstrumentManagementDialog(final Frame parent, final boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        instrumentDetailsTableScrollPane.getViewport().setOpaque(false);
        setLocationRelativeTo(parent);
    }

    public JButton getAddInstrumentButton() {
        return addInstrumentButton;
    }

    public JButton getDeleteInstrumentButton() {
        return deleteInstrumentButton;
    }

    public JList getInstrumentList() {
        return instrumentList;
    }  

    public JTable getInstrumentDetailsTable() {
        return instrumentDetailsTable;
    }

    public JButton getEditInstrumentButton() {
        return instrumentEditButton;
    }        

    public JButton getCloseInstrumentManagementButton() {
        return closeInstrumentManagementButton;
    }            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instrumentCrudPanel = new javax.swing.JPanel();
        instrumentOverviewPanel = new javax.swing.JPanel();
        instrumentListScrollPane = new javax.swing.JScrollPane();
        instrumentList = new javax.swing.JList();
        addInstrumentButton = new javax.swing.JButton();
        deleteInstrumentButton = new javax.swing.JButton();
        instrumentEditButton = new javax.swing.JButton();
        instrumentDetailPanel = new javax.swing.JPanel();
        instrumentDetailsTableScrollPane = new javax.swing.JScrollPane();
        instrumentDetailsTable = new javax.swing.JTable();
        closeInstrumentManagementButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("instrument management overview");

        instrumentCrudPanel.setBackground(new java.awt.Color(255, 255, 255));

        instrumentOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("overview"));
        instrumentOverviewPanel.setOpaque(false);
        instrumentOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        instrumentListScrollPane.setOpaque(false);

        instrumentListScrollPane.setViewportView(instrumentList);

        addInstrumentButton.setText("add...");
        addInstrumentButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addInstrumentButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addInstrumentButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deleteInstrumentButton.setText("delete");
        deleteInstrumentButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteInstrumentButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteInstrumentButton.setPreferredSize(new java.awt.Dimension(80, 25));

        instrumentEditButton.setText("edit...");
        instrumentEditButton.setToolTipText("save or update the selected instrument");
        instrumentEditButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout instrumentOverviewPanelLayout = new javax.swing.GroupLayout(instrumentOverviewPanel);
        instrumentOverviewPanel.setLayout(instrumentOverviewPanelLayout);
        instrumentOverviewPanelLayout.setHorizontalGroup(
            instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrumentListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(instrumentEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        instrumentOverviewPanelLayout.setVerticalGroup(
            instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instrumentListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addGroup(instrumentOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instrumentEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        instrumentDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("detail"));
        instrumentDetailPanel.setOpaque(false);
        instrumentDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        instrumentDetailsTableScrollPane.setOpaque(false);

        instrumentDetailsTable.setOpaque(false);
        instrumentDetailsTableScrollPane.setViewportView(instrumentDetailsTable);

        javax.swing.GroupLayout instrumentDetailPanelLayout = new javax.swing.GroupLayout(instrumentDetailPanel);
        instrumentDetailPanel.setLayout(instrumentDetailPanelLayout);
        instrumentDetailPanelLayout.setHorizontalGroup(
            instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrumentDetailsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        instrumentDetailPanelLayout.setVerticalGroup(
            instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrumentDetailsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        closeInstrumentManagementButton.setText("close");
        closeInstrumentManagementButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout instrumentCrudPanelLayout = new javax.swing.GroupLayout(instrumentCrudPanel);
        instrumentCrudPanel.setLayout(instrumentCrudPanelLayout);
        instrumentCrudPanelLayout.setHorizontalGroup(
            instrumentCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentCrudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(instrumentOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addComponent(instrumentDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instrumentCrudPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeInstrumentManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        instrumentCrudPanelLayout.setVerticalGroup(
            instrumentCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instrumentCrudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrumentOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instrumentDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeInstrumentManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(instrumentCrudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(instrumentCrudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInstrumentButton;
    private javax.swing.JButton closeInstrumentManagementButton;
    private javax.swing.JButton deleteInstrumentButton;
    private javax.swing.JPanel instrumentCrudPanel;
    private javax.swing.JPanel instrumentDetailPanel;
    private javax.swing.JTable instrumentDetailsTable;
    private javax.swing.JScrollPane instrumentDetailsTableScrollPane;
    private javax.swing.JButton instrumentEditButton;
    private javax.swing.JList instrumentList;
    private javax.swing.JScrollPane instrumentListScrollPane;
    private javax.swing.JPanel instrumentOverviewPanel;
    // End of variables declaration//GEN-END:variables
    
}
