package com.compomics.colims.client.view.admin.protocol;

import com.compomics.colims.client.compoment.DualList;
import com.compomics.colims.model.ProtocolCvTerm;
import java.awt.Dialog;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author Niels Hulstaert
 */
public class ProtocolEditDialog extends javax.swing.JDialog {
    
    /**
     * Creates new form InstrumentCvDialog
     */
    public ProtocolEditDialog(final Dialog parent, final boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        setLocationRelativeTo(parent);
    }

    public JButton getCloseProtocolEditButton() {
        return closeProtocolEditButton;
    }

    public DualList<ProtocolCvTerm> getCvTermDualList() {
        return cvTermDualList;
    }

    public JList getCvTermSummaryList() {
        return cvTermSummaryList;
    }

    public JButton getProtocolCvTermsCrudButton() {
        return protocolCvTermsCrudButton;
    }

    public JButton getProtocolSaveOrUpdateButton() {
        return protocolSaveOrUpdateButton;
    }  

    public JTextField getNameTextField() {
        return nameTextField;
    } 

    public JLabel getProtocolStateInfoLabel() {
        return protocolStateInfoLabel;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        protocolEditPanel = new javax.swing.JPanel();
        closeProtocolEditButton = new javax.swing.JButton();
        protocolSaveOrUpdateButton = new javax.swing.JButton();
        cvTermsPanel = new javax.swing.JPanel();
        cvTermSummaryScrollPane = new javax.swing.JScrollPane();
        cvTermSummaryList = new javax.swing.JList();
        cvTermDualList = new com.compomics.colims.client.compoment.DualList<ProtocolCvTerm>();
        protocolCvTermsCrudButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        protocolStateInfoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("protocol management");

        protocolEditPanel.setBackground(new java.awt.Color(255, 255, 255));

        closeProtocolEditButton.setText("close");
        closeProtocolEditButton.setMaximumSize(new java.awt.Dimension(80, 25));
        closeProtocolEditButton.setMinimumSize(new java.awt.Dimension(80, 25));
        closeProtocolEditButton.setPreferredSize(new java.awt.Dimension(80, 25));

        protocolSaveOrUpdateButton.setText("save");
        protocolSaveOrUpdateButton.setMaximumSize(new java.awt.Dimension(80, 25));
        protocolSaveOrUpdateButton.setMinimumSize(new java.awt.Dimension(80, 25));
        protocolSaveOrUpdateButton.setPreferredSize(new java.awt.Dimension(80, 25));

        cvTermsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("CV terms"));
        cvTermsPanel.setOpaque(false);

        cvTermSummaryScrollPane.setOpaque(false);

        cvTermSummaryScrollPane.setViewportView(cvTermSummaryList);

        protocolCvTermsCrudButton.setText("edit...");
        protocolCvTermsCrudButton.setToolTipText("edit the available CV terms of the selected CV term type");
        protocolCvTermsCrudButton.setMaximumSize(new java.awt.Dimension(80, 25));
        protocolCvTermsCrudButton.setMinimumSize(new java.awt.Dimension(80, 25));
        protocolCvTermsCrudButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout cvTermsPanelLayout = new javax.swing.GroupLayout(cvTermsPanel);
        cvTermsPanel.setLayout(cvTermsPanelLayout);
        cvTermsPanelLayout.setHorizontalGroup(
            cvTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cvTermsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cvTermSummaryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cvTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(protocolCvTermsCrudButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvTermDualList, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        cvTermsPanelLayout.setVerticalGroup(
            cvTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cvTermsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cvTermsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cvTermSummaryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(cvTermDualList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(protocolCvTermsCrudButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nameLabel.setText("name");

        protocolStateInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        protocolStateInfoLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout protocolEditPanelLayout = new javax.swing.GroupLayout(protocolEditPanel);
        protocolEditPanel.setLayout(protocolEditPanelLayout);
        protocolEditPanelLayout.setHorizontalGroup(
            protocolEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(protocolEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(protocolEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cvTermsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, protocolEditPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(protocolSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeProtocolEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(protocolStateInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(protocolEditPanelLayout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        protocolEditPanelLayout.setVerticalGroup(
            protocolEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(protocolEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(protocolStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(protocolEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cvTermsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(protocolEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocolSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeProtocolEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(protocolEditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(protocolEditPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeProtocolEditButton;
    private com.compomics.colims.client.compoment.DualList<ProtocolCvTerm> cvTermDualList;
    private javax.swing.JList cvTermSummaryList;
    private javax.swing.JScrollPane cvTermSummaryScrollPane;
    private javax.swing.JPanel cvTermsPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton protocolCvTermsCrudButton;
    private javax.swing.JPanel protocolEditPanel;
    private javax.swing.JButton protocolSaveOrUpdateButton;
    private javax.swing.JLabel protocolStateInfoLabel;
    // End of variables declaration//GEN-END:variables
    
}
