/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.colims.core.storage.processing.storagequeue.storagetask;

import com.compomics.colims.core.storage.enums.StorageState;

/**
 *
 * @author Kenneth
 */
public class StorageTask {

    private final long taskID;
    private final String fileLocation;
    private StorageState state = StorageState.WAITING;

    /**
     *
     * @param taskID the taskID of this storageTask. If this is not yet known,
     * it has to be generated by the StorageQueue
     * @param fileLocation the path to the file that needs to be stored
     */
    public StorageTask(long taskID, String fileLocation) {
        this.taskID = taskID;
        this.fileLocation = fileLocation;
    }

    public long getTaskID() {
        return taskID;
    }

    public String getFileLocation() {
        return fileLocation;
    }

    public StorageState getState() {
        return state;
    }

    public void setState(StorageState state) {
        this.state = state;
    }

}
