package com.compomics.colims.client.view.admin;

import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Niels Hulstaert
 */
public class CvParamManagementDialog extends javax.swing.JDialog {

     /**
     * Dialog constructor.
     *
     * @param parent the parent frame
     * @param modal the modal boolean
     */
    public CvParamManagementDialog(final Frame parent, final boolean modal) {
        super(parent, modal);

        initComponents();

        cvParamTableScrollPane.getViewport().setOpaque(false);
        setLocationRelativeTo(parent);
    }

    public JTable getCvParamTable() {
        return cvParamTable;
    }

    public JTextField getAccessionTextField() {
        return accessionTextField;
    }

    public JButton getAddCvParamButton() {
        return addCvParamButton;
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public JLabel getCvParamStateInfoLabel() {
        return cvParamStateInfoLabel;
    }

    public JButton getDeleteCvParamButton() {
        return deleteCvParamButton;
    }

    public JTextField getNameTextField() {
        return nameTextField;
    }

    public JTextField getOntologyLabelTextField() {
        return ontologyLabelTextField;
    }

    public JTextField getOntologyTextField() {
        return ontologyTextField;
    }

    public JButton getSaveOrUpdateButton() {
        return saveOrUpdateButton;
    }

    public JTextArea getDefinitionTextArea() {
        return definitionTextArea;
    }

    public JButton getEditUsingOlsCvParamButton() {
        return editUsingOlsCvParamButton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cvParamCrudPanel = new javax.swing.JPanel();
        cvParamOverviewPanel = new javax.swing.JPanel();
        addCvParamButton = new javax.swing.JButton();
        deleteCvParamButton = new javax.swing.JButton();
        cvParamTableScrollPane = new javax.swing.JScrollPane();
        cvParamTable = new javax.swing.JTable();
        cvParamDetailPanel = new javax.swing.JPanel();
        ontologyLabel = new javax.swing.JLabel();
        ontologyTextField = new javax.swing.JTextField();
        ontologyLabelLabel = new javax.swing.JLabel();
        ontologyLabelTextField = new javax.swing.JTextField();
        accessionLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        accessionTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        saveOrUpdateButton = new javax.swing.JButton();
        cvParamStateInfoLabel = new javax.swing.JLabel();
        definitionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        definitionTextArea = new javax.swing.JTextArea();
        editUsingOlsCvParamButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CV param management");

        cvParamCrudPanel.setBackground(new java.awt.Color(255, 255, 255));

        cvParamOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Overview"));
        cvParamOverviewPanel.setOpaque(false);
        cvParamOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        addCvParamButton.setText("add...");
        addCvParamButton.setToolTipText("add a CV param with the OLS dialog");
        addCvParamButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addCvParamButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addCvParamButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deleteCvParamButton.setText("delete");
        deleteCvParamButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteCvParamButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteCvParamButton.setPreferredSize(new java.awt.Dimension(80, 25));

        cvParamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        cvParamTable.setOpaque(false);
        cvParamTableScrollPane.setViewportView(cvParamTable);

        javax.swing.GroupLayout cvParamOverviewPanelLayout = new javax.swing.GroupLayout(cvParamOverviewPanel);
        cvParamOverviewPanel.setLayout(cvParamOverviewPanelLayout);
        cvParamOverviewPanelLayout.setHorizontalGroup(
            cvParamOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cvParamOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cvParamOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cvParamOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 336, Short.MAX_VALUE)
                        .addComponent(addCvParamButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteCvParamButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cvParamTableScrollPane))
                .addContainerGap())
        );
        cvParamOverviewPanelLayout.setVerticalGroup(
            cvParamOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cvParamOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cvParamTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cvParamOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCvParamButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCvParamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cvParamDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));
        cvParamDetailPanel.setOpaque(false);
        cvParamDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        ontologyLabel.setText("Ontology Name");

        ontologyTextField.setEnabled(false);

        ontologyLabelLabel.setText("Ontology Label");

        ontologyLabelTextField.setEnabled(false);

        accessionLabel.setText("Accession");

        nameLabel.setText("Name");

        accessionTextField.setEnabled(false);

        nameTextField.setEnabled(false);

        saveOrUpdateButton.setText("save");
        saveOrUpdateButton.setMaximumSize(new java.awt.Dimension(80, 25));
        saveOrUpdateButton.setMinimumSize(new java.awt.Dimension(80, 25));
        saveOrUpdateButton.setPreferredSize(new java.awt.Dimension(80, 25));

        cvParamStateInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cvParamStateInfoLabel.setForeground(new java.awt.Color(255, 0, 0));
        cvParamStateInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cvParamStateInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        cvParamStateInfoLabel.setMaximumSize(new java.awt.Dimension(100, 20));
        cvParamStateInfoLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        cvParamStateInfoLabel.setPreferredSize(new java.awt.Dimension(100, 20));

        definitionLabel.setText("Definition");

        definitionTextArea.setEditable(false);
        definitionTextArea.setColumns(20);
        definitionTextArea.setLineWrap(true);
        definitionTextArea.setRows(5);
        definitionTextArea.setEnabled(false);
        jScrollPane1.setViewportView(definitionTextArea);

        editUsingOlsCvParamButton.setText("edit...");
        editUsingOlsCvParamButton.setToolTipText("add a CV param with the OLS dialog");
        editUsingOlsCvParamButton.setMaximumSize(new java.awt.Dimension(80, 25));
        editUsingOlsCvParamButton.setMinimumSize(new java.awt.Dimension(80, 25));
        editUsingOlsCvParamButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout cvParamDetailPanelLayout = new javax.swing.GroupLayout(cvParamDetailPanel);
        cvParamDetailPanel.setLayout(cvParamDetailPanelLayout);
        cvParamDetailPanelLayout.setHorizontalGroup(
            cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cvParamDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cvParamDetailPanelLayout.createSequentialGroup()
                        .addComponent(cvParamStateInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editUsingOlsCvParamButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cvParamDetailPanelLayout.createSequentialGroup()
                        .addGroup(cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accessionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ontologyLabelLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(definitionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ontologyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                            .addComponent(accessionTextField)
                            .addComponent(nameTextField)
                            .addComponent(ontologyTextField)
                            .addComponent(ontologyLabelTextField))))
                .addContainerGap())
        );
        cvParamDetailPanelLayout.setVerticalGroup(
            cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cvParamDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ontologyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ontologyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ontologyLabelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ontologyLabelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accessionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addGroup(cvParamDetailPanelLayout.createSequentialGroup()
                        .addComponent(definitionLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cvParamDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editUsingOlsCvParamButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cvParamStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cancelButton.setText("cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(80, 25));
        cancelButton.setMinimumSize(new java.awt.Dimension(80, 25));
        cancelButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout cvParamCrudPanelLayout = new javax.swing.GroupLayout(cvParamCrudPanel);
        cvParamCrudPanel.setLayout(cvParamCrudPanelLayout);
        cvParamCrudPanelLayout.setHorizontalGroup(
            cvParamCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cvParamCrudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cvParamCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cvParamCrudPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cvParamOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(cvParamDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                .addContainerGap())
        );
        cvParamCrudPanelLayout.setVerticalGroup(
            cvParamCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cvParamCrudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cvParamOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cvParamDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cvParamCrudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cvParamCrudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accessionLabel;
    private javax.swing.JTextField accessionTextField;
    private javax.swing.JButton addCvParamButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel cvParamCrudPanel;
    private javax.swing.JPanel cvParamDetailPanel;
    private javax.swing.JPanel cvParamOverviewPanel;
    private javax.swing.JLabel cvParamStateInfoLabel;
    private javax.swing.JTable cvParamTable;
    private javax.swing.JScrollPane cvParamTableScrollPane;
    private javax.swing.JLabel definitionLabel;
    private javax.swing.JTextArea definitionTextArea;
    private javax.swing.JButton deleteCvParamButton;
    private javax.swing.JButton editUsingOlsCvParamButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel ontologyLabel;
    private javax.swing.JLabel ontologyLabelLabel;
    private javax.swing.JTextField ontologyLabelTextField;
    private javax.swing.JTextField ontologyTextField;
    private javax.swing.JButton saveOrUpdateButton;
    // End of variables declaration//GEN-END:variables

}
