package com.compomics.colims.client.view.admin;

import java.awt.Color;
import java.awt.Frame;

/**
 *
 * @author niels
 */
public class MetaDataManagementDialog extends javax.swing.JDialog {

    /**
     * Creates new form InstrumentCvDialog
     */
    public MetaDataManagementDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instrumentCrudTabbedPane = new javax.swing.JTabbedPane();
        instrumentCrudPanel = new javax.swing.JPanel();
        instrumentOverviewPanel = new javax.swing.JPanel();
        instrumentListScrollPane = new javax.swing.JScrollPane();
        instrumentList = new javax.swing.JList();
        addInstrumentButton = new javax.swing.JButton();
        deleteInstrumentButton = new javax.swing.JButton();
        instrumentDetailPanel = new javax.swing.JPanel();
        instrumentTypeLabel = new javax.swing.JLabel();
        instrumentSourceLabel = new javax.swing.JLabel();
        instrumentDetectorLabel = new javax.swing.JLabel();
        instrumentTypeTextField = new javax.swing.JTextField();
        instrumentSourceTextField = new javax.swing.JTextField();
        instrumentDetectorTextField = new javax.swing.JTextField();
        instrumentNameLabel = new javax.swing.JLabel();
        instrumentNameTextField = new javax.swing.JTextField();
        userSaveOrUpdateButton = new javax.swing.JButton();
        userStateInfoLabel = new javax.swing.JLabel();
        sourceOlsButton = new javax.swing.JButton();
        detectorOlsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        instrumentOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Overview"));
        instrumentOverviewPanel.setOpaque(false);
        instrumentOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        instrumentListScrollPane.setViewportView(instrumentList);

        addInstrumentButton.setText("add");
        addInstrumentButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addInstrumentButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addInstrumentButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deleteInstrumentButton.setText("delete");
        deleteInstrumentButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteInstrumentButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteInstrumentButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout instrumentOverviewPanelLayout = new javax.swing.GroupLayout(instrumentOverviewPanel);
        instrumentOverviewPanel.setLayout(instrumentOverviewPanelLayout);
        instrumentOverviewPanelLayout.setHorizontalGroup(
            instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrumentListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        instrumentOverviewPanelLayout.setVerticalGroup(
            instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(instrumentOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(instrumentListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        instrumentDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));
        instrumentDetailPanel.setOpaque(false);
        instrumentDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        instrumentTypeLabel.setText("type");

        instrumentSourceLabel.setText("source");

        instrumentDetectorLabel.setText("detector");

        instrumentNameLabel.setText("ontology");
        instrumentNameLabel.setPreferredSize(new java.awt.Dimension(48, 14));

        userSaveOrUpdateButton.setText("save");
        userSaveOrUpdateButton.setMaximumSize(new java.awt.Dimension(80, 25));
        userSaveOrUpdateButton.setMinimumSize(new java.awt.Dimension(80, 25));
        userSaveOrUpdateButton.setPreferredSize(new java.awt.Dimension(80, 25));

        userStateInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userStateInfoLabel.setForeground(new java.awt.Color(255, 0, 0));
        userStateInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        userStateInfoLabel.setMaximumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel.setPreferredSize(new java.awt.Dimension(100, 20));

        sourceOlsButton.setText("OLS");

        detectorOlsButton.setText("OLS");

        javax.swing.GroupLayout instrumentDetailPanelLayout = new javax.swing.GroupLayout(instrumentDetailPanel);
        instrumentDetailPanel.setLayout(instrumentDetailPanelLayout);
        instrumentDetailPanelLayout.setHorizontalGroup(
            instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(instrumentDetailPanelLayout.createSequentialGroup()
                        .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(instrumentDetectorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instrumentSourceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instrumentTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instrumentNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(instrumentSourceTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(instrumentTypeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instrumentNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instrumentDetectorTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceOlsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(detectorOlsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addComponent(userStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(instrumentDetailPanelLayout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(userSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        instrumentDetailPanelLayout.setVerticalGroup(
            instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrumentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instrumentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrumentTypeLabel)
                    .addComponent(instrumentTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrumentSourceLabel)
                    .addComponent(instrumentSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceOlsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrumentDetectorLabel)
                    .addComponent(instrumentDetectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detectorOlsButton))
                .addGap(19, 19, 19)
                .addComponent(userSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout instrumentCrudPanelLayout = new javax.swing.GroupLayout(instrumentCrudPanel);
        instrumentCrudPanel.setLayout(instrumentCrudPanelLayout);
        instrumentCrudPanelLayout.setHorizontalGroup(
            instrumentCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instrumentOverviewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
            .addComponent(instrumentDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );
        instrumentCrudPanelLayout.setVerticalGroup(
            instrumentCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instrumentCrudPanelLayout.createSequentialGroup()
                .addComponent(instrumentOverviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instrumentDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        instrumentCrudTabbedPane.addTab("Instrument", instrumentCrudPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(instrumentCrudTabbedPane)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(instrumentCrudTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInstrumentButton;
    private javax.swing.JButton deleteInstrumentButton;
    private javax.swing.JButton detectorOlsButton;
    private javax.swing.JPanel instrumentCrudPanel;
    private javax.swing.JTabbedPane instrumentCrudTabbedPane;
    private javax.swing.JPanel instrumentDetailPanel;
    private javax.swing.JLabel instrumentDetectorLabel;
    private javax.swing.JTextField instrumentDetectorTextField;
    private javax.swing.JList instrumentList;
    private javax.swing.JScrollPane instrumentListScrollPane;
    private javax.swing.JLabel instrumentNameLabel;
    private javax.swing.JTextField instrumentNameTextField;
    private javax.swing.JPanel instrumentOverviewPanel;
    private javax.swing.JLabel instrumentSourceLabel;
    private javax.swing.JTextField instrumentSourceTextField;
    private javax.swing.JLabel instrumentTypeLabel;
    private javax.swing.JTextField instrumentTypeTextField;
    private javax.swing.JButton sourceOlsButton;
    private javax.swing.JButton userSaveOrUpdateButton;
    private javax.swing.JLabel userStateInfoLabel;
    // End of variables declaration//GEN-END:variables
}
