package com.compomics.colims.client.view.admin;

import com.compomics.colims.client.controller.Controllable;
import com.compomics.colims.client.controller.admin.MetadataManagementController;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Window;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;
import no.uib.olsdialog.OLSInputable;

/**
 *
 * @author niels
 */
public class MetaDataManagementDialog extends javax.swing.JDialog {

    private MetadataManagementController metadataManagementController;
    
    /**
     * Creates new form InstrumentCvDialog
     */
    public MetaDataManagementDialog(Frame parent, boolean modal, MetadataManagementController metadataManagementController) {
        super(parent, modal);
        this.metadataManagementController = metadataManagementController;
        
        initComponents();
        
        this.getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(parent);
    }

    public JButton getAddAnalyzerButton() {
        return addAnalyzerButton;
    }

    public JButton getAddInstrumentButton() {
        return addInstrumentButton;
    }

    public JList getAnalyzerList() {
        return analyzerList;
    }

    public JButton getDeleteInstrumentButton() {
        return deleteInstrumentButton;
    }

    public JTextField getInstrumentDetectorTextField() {
        return instrumentDetectorTextField;
    }

    public JList getInstrumentList() {
        return instrumentList;
    }

    public JTextField getInstrumentNameTextField() {
        return instrumentNameTextField;
    }

    public JTextField getInstrumentSourceTextField() {
        return instrumentSourceTextField;
    }

    public JTextField getInstrumentTypeTextField() {
        return instrumentTypeTextField;
    }

    public JButton getDetectorOlsButton() {
        return detectorOlsButton;
    }

    public JButton getInstrumentSaveOrUpdateButton() {
        return instrumentSaveOrUpdateButton;
    }

    public JLabel getInstrumentStateInfoLabel() {
        return instrumentStateInfoLabel;
    }

    public JButton getSourceOlsButton() {
        return sourceOlsButton;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instrumentCrudTabbedPane = new javax.swing.JTabbedPane();
        instrumentCrudPanel = new javax.swing.JPanel();
        instrumentOverviewPanel = new javax.swing.JPanel();
        instrumentListScrollPane = new javax.swing.JScrollPane();
        instrumentList = new javax.swing.JList();
        addInstrumentButton = new javax.swing.JButton();
        deleteInstrumentButton = new javax.swing.JButton();
        instrumentDetailPanel = new javax.swing.JPanel();
        instrumentTypeLabel = new javax.swing.JLabel();
        instrumentSourceLabel = new javax.swing.JLabel();
        instrumentDetectorLabel = new javax.swing.JLabel();
        instrumentTypeTextField = new javax.swing.JTextField();
        instrumentSourceTextField = new javax.swing.JTextField();
        instrumentDetectorTextField = new javax.swing.JTextField();
        instrumentNameLabel = new javax.swing.JLabel();
        instrumentNameTextField = new javax.swing.JTextField();
        instrumentSaveOrUpdateButton = new javax.swing.JButton();
        instrumentStateInfoLabel = new javax.swing.JLabel();
        sourceOlsButton = new javax.swing.JButton();
        detectorOlsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        analyzerList = new javax.swing.JList();
        analyzerListLabel = new javax.swing.JLabel();
        addAnalyzerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        instrumentOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Overview"));
        instrumentOverviewPanel.setOpaque(false);
        instrumentOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        instrumentListScrollPane.setViewportView(instrumentList);

        addInstrumentButton.setText("add");
        addInstrumentButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addInstrumentButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addInstrumentButton.setPreferredSize(new java.awt.Dimension(80, 25));
        addInstrumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstrumentButtonActionPerformed(evt);
            }
        });

        deleteInstrumentButton.setText("delete");
        deleteInstrumentButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteInstrumentButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteInstrumentButton.setPreferredSize(new java.awt.Dimension(80, 25));
        deleteInstrumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInstrumentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout instrumentOverviewPanelLayout = new javax.swing.GroupLayout(instrumentOverviewPanel);
        instrumentOverviewPanel.setLayout(instrumentOverviewPanelLayout);
        instrumentOverviewPanelLayout.setHorizontalGroup(
            instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrumentListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        instrumentOverviewPanelLayout.setVerticalGroup(
            instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(instrumentOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(instrumentListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addContainerGap())
        );

        instrumentDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));
        instrumentDetailPanel.setOpaque(false);
        instrumentDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        instrumentTypeLabel.setText("type");

        instrumentSourceLabel.setText("source");

        instrumentDetectorLabel.setText("detector");

        instrumentNameLabel.setText("name");
        instrumentNameLabel.setPreferredSize(new java.awt.Dimension(48, 14));

        instrumentSaveOrUpdateButton.setText("save");
        instrumentSaveOrUpdateButton.setMaximumSize(new java.awt.Dimension(80, 25));
        instrumentSaveOrUpdateButton.setMinimumSize(new java.awt.Dimension(80, 25));
        instrumentSaveOrUpdateButton.setPreferredSize(new java.awt.Dimension(80, 25));

        instrumentStateInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        instrumentStateInfoLabel.setForeground(new java.awt.Color(255, 0, 0));
        instrumentStateInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        instrumentStateInfoLabel.setMaximumSize(new java.awt.Dimension(100, 20));
        instrumentStateInfoLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        instrumentStateInfoLabel.setPreferredSize(new java.awt.Dimension(100, 20));

        sourceOlsButton.setText("OLS");

        detectorOlsButton.setText("OLS");

        jScrollPane1.setViewportView(analyzerList);

        analyzerListLabel.setText("analyzer(s)");

        addAnalyzerButton.setText("add analyzer");
        addAnalyzerButton.setPreferredSize(new java.awt.Dimension(80, 25));
        addAnalyzerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnalyzerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout instrumentDetailPanelLayout = new javax.swing.GroupLayout(instrumentDetailPanel);
        instrumentDetailPanel.setLayout(instrumentDetailPanelLayout);
        instrumentDetailPanelLayout.setHorizontalGroup(
            instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(instrumentDetailPanelLayout.createSequentialGroup()
                        .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(instrumentDetectorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instrumentSourceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instrumentTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instrumentNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(instrumentSourceTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(instrumentTypeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instrumentNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instrumentDetectorTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceOlsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(detectorOlsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addComponent(instrumentStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(instrumentDetailPanelLayout.createSequentialGroup()
                        .addComponent(analyzerListLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addAnalyzerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instrumentDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(instrumentSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        instrumentDetailPanelLayout.setVerticalGroup(
            instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instrumentStateInfoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(analyzerListLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addAnalyzerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(instrumentDetailPanelLayout.createSequentialGroup()
                        .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instrumentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instrumentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instrumentTypeLabel)
                            .addComponent(instrumentTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instrumentSourceLabel)
                            .addComponent(instrumentSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sourceOlsButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(instrumentDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(instrumentDetectorLabel)
                            .addComponent(instrumentDetectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detectorOlsButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(instrumentSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout instrumentCrudPanelLayout = new javax.swing.GroupLayout(instrumentCrudPanel);
        instrumentCrudPanel.setLayout(instrumentCrudPanelLayout);
        instrumentCrudPanelLayout.setHorizontalGroup(
            instrumentCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instrumentOverviewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
            .addComponent(instrumentDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        instrumentCrudPanelLayout.setVerticalGroup(
            instrumentCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instrumentCrudPanelLayout.createSequentialGroup()
                .addComponent(instrumentOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instrumentDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        instrumentCrudTabbedPane.addTab("Instrument", instrumentCrudPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(instrumentCrudTabbedPane)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(instrumentCrudTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addInstrumentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstrumentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addInstrumentButtonActionPerformed

    private void deleteInstrumentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInstrumentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteInstrumentButtonActionPerformed

    private void addAnalyzerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnalyzerButtonActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_addAnalyzerButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAnalyzerButton;
    private javax.swing.JButton addInstrumentButton;
    private javax.swing.JList analyzerList;
    private javax.swing.JLabel analyzerListLabel;
    private javax.swing.JButton deleteInstrumentButton;
    private javax.swing.JButton detectorOlsButton;
    private javax.swing.JPanel instrumentCrudPanel;
    private javax.swing.JTabbedPane instrumentCrudTabbedPane;
    private javax.swing.JPanel instrumentDetailPanel;
    private javax.swing.JLabel instrumentDetectorLabel;
    private javax.swing.JTextField instrumentDetectorTextField;
    private javax.swing.JList instrumentList;
    private javax.swing.JScrollPane instrumentListScrollPane;
    private javax.swing.JLabel instrumentNameLabel;
    private javax.swing.JTextField instrumentNameTextField;
    private javax.swing.JPanel instrumentOverviewPanel;
    private javax.swing.JButton instrumentSaveOrUpdateButton;
    private javax.swing.JLabel instrumentSourceLabel;
    private javax.swing.JTextField instrumentSourceTextField;
    private javax.swing.JLabel instrumentStateInfoLabel;
    private javax.swing.JLabel instrumentTypeLabel;
    private javax.swing.JTextField instrumentTypeTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sourceOlsButton;
    // End of variables declaration//GEN-END:variables
    
}
