/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.colims.client.view.admin;

import com.compomics.colims.client.compoment.DualList;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * This dialog is used for searching ontology terms with the Ontology Lookup
 * Service (OLS).
 *
 * @author Niels Hulstaert
 */
public class OlsDialog extends javax.swing.JDialog {

    /**
     * Dialog constructor.
     *
     * @param parent the parent frame
     * @param modal the modal boolean
     */
    public OlsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        searchResultsScrollPane.getViewport().setOpaque(false);
    }

    public JRadioButton getAllOntologiesRadioButton() {
        return allOntologiesRadioButton;
    }

    public JCheckBox getAnnotationPropertiesCheckBox() {
        return annotationPropertiesCheckBox;
    }

    public JButton getCloseButton() {
        return closeButton;
    }

    public JCheckBox getDescriptionCheckBox() {
        return descriptionCheckBox;
    }

    public JButton getGetAllOntologiesButton() {
        return getAllOntologiesButton;
    }

    public JCheckBox getLabelCheckBox() {
        return labelCheckBox;
    }

    public DualList getOntologiesDualList() {
        return ontologiesDualList;
    }

    public JRadioButton getPreselectedOntologiesRadioButton() {
        return preselectedOntologiesRadioButton;
    }

    public JButton getSearchButton() {
        return searchButton;
    }

    public JTextField getSearchInputTextField() {
        return searchInputTextField;
    }

    public JButton getSelectButton() {
        return selectButton;
    }

    public JCheckBox getSynonymCheckBox() {
        return synonymCheckBox;
    }

    public JRadioButton getCustomFieldsRadioButton() {
        return customFieldsRadioButton;
    }

    public JRadioButton getDefaultFieldsRadioButton() {
        return defaultFieldsRadioButton;
    }

    public JTable getSearchResultTable() {
        return searchResultTable;
    }

    public ButtonGroup getOntologiesSelectionButtonGroup() {
        return ontologiesSelectionButtonGroup;
    }

    public ButtonGroup getSearchFieldsSelectionButtonGroup() {
        return searchFieldsSelectionButtonGroup;
    }

    public JButton getFirstResultPageButton() {
        return firstResultPageButton;
    }

    public JButton getLastResultPageButton() {
        return lastResultPageButton;
    }

    public JButton getNextResultPageButton() {
        return nextResultPageButton;
    }

    public JButton getPreviousResultPageButton() {
        return previousResultPageButton;
    }

    public JLabel getSearchResultPageLabel() {
        return searchResultPageLabel;
    }

    public JCheckBox getIdentifierCheckBox() {
        return identifierCheckBox;
    }

    public JTextField getOntologyNamespaceTextField() {
        return ontologyNamespaceTextField;
    }

    public JTextField getTermAccessionTextField() {
        return termAccessionTextField;
    }

    public JTextArea getTermDescriptionTextArea() {
        return termDescriptionTextArea;
    }

    public JTextField getTermLabelTextField() {
        return termLabelTextField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ontologiesSelectionButtonGroup = new javax.swing.ButtonGroup();
        searchFieldsSelectionButtonGroup = new javax.swing.ButtonGroup();
        olsParentPanel = new javax.swing.JPanel();
        olsTabbedPane = new javax.swing.JTabbedPane();
        searchPanel = new javax.swing.JPanel();
        searchInputLabel = new javax.swing.JLabel();
        searchInputTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        searchResultsPanel = new javax.swing.JPanel();
        searchResultsScrollPane = new javax.swing.JScrollPane();
        searchResultTable = new javax.swing.JTable();
        lastResultPageButton = new javax.swing.JButton();
        nextResultPageButton = new javax.swing.JButton();
        previousResultPageButton = new javax.swing.JButton();
        firstResultPageButton = new javax.swing.JButton();
        searchResultPageLabel = new javax.swing.JLabel();
        termDetailPanel = new javax.swing.JPanel();
        ontologyNamespaceLabel = new javax.swing.JLabel();
        ontologyNamespaceTextField = new javax.swing.JTextField();
        termLabelLabel = new javax.swing.JLabel();
        termLabelTextField = new javax.swing.JTextField();
        termDescriptionLabel = new javax.swing.JLabel();
        termAccessionLabel = new javax.swing.JLabel();
        termAccessionTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        termDescriptionTextArea = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();
        searchSettingsPanel = new javax.swing.JPanel();
        searchOntologiesPanel = new javax.swing.JPanel();
        searchOntologiesLabel = new javax.swing.JLabel();
        allOntologiesRadioButton = new javax.swing.JRadioButton();
        preselectedOntologiesRadioButton = new javax.swing.JRadioButton();
        ontologiesDualList = new com.compomics.colims.client.compoment.DualList();
        getAllOntologiesButton = new javax.swing.JButton();
        searchFieldsPanel = new javax.swing.JPanel();
        labelCheckBox = new javax.swing.JCheckBox();
        synonymCheckBox = new javax.swing.JCheckBox();
        descriptionCheckBox = new javax.swing.JCheckBox();
        identifierCheckBox = new javax.swing.JCheckBox();
        annotationPropertiesCheckBox = new javax.swing.JCheckBox();
        searchFieldsLabel = new javax.swing.JLabel();
        defaultFieldsRadioButton = new javax.swing.JRadioButton();
        customFieldsRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ontology Lookup Service (OLS) dialog");

        olsParentPanel.setBackground(new java.awt.Color(255, 255, 255));

        olsTabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        searchPanel.setOpaque(false);

        searchInputLabel.setText("Search input");

        searchButton.setText("search");
        searchButton.setMaximumSize(new java.awt.Dimension(80, 25));
        searchButton.setMinimumSize(new java.awt.Dimension(80, 25));
        searchButton.setPreferredSize(new java.awt.Dimension(80, 25));

        searchResultsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search results"));
        searchResultsPanel.setOpaque(false);

        searchResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        searchResultTable.setOpaque(false);
        searchResultsScrollPane.setViewportView(searchResultTable);

        lastResultPageButton.setText(">>");
        lastResultPageButton.setMaximumSize(new java.awt.Dimension(48, 25));
        lastResultPageButton.setMinimumSize(new java.awt.Dimension(48, 25));
        lastResultPageButton.setPreferredSize(new java.awt.Dimension(48, 25));

        nextResultPageButton.setText(">");
        nextResultPageButton.setMaximumSize(new java.awt.Dimension(38, 25));
        nextResultPageButton.setMinimumSize(new java.awt.Dimension(38, 25));
        nextResultPageButton.setPreferredSize(new java.awt.Dimension(38, 25));

        previousResultPageButton.setText("<");
        previousResultPageButton.setMaximumSize(new java.awt.Dimension(38, 25));
        previousResultPageButton.setMinimumSize(new java.awt.Dimension(38, 25));
        previousResultPageButton.setPreferredSize(new java.awt.Dimension(38, 25));

        firstResultPageButton.setText("<<");
        firstResultPageButton.setMaximumSize(new java.awt.Dimension(48, 25));
        firstResultPageButton.setMinimumSize(new java.awt.Dimension(48, 25));
        firstResultPageButton.setPreferredSize(new java.awt.Dimension(48, 25));

        searchResultPageLabel.setMaximumSize(new java.awt.Dimension(60, 27));
        searchResultPageLabel.setMinimumSize(new java.awt.Dimension(60, 27));
        searchResultPageLabel.setPreferredSize(new java.awt.Dimension(60, 27));

        javax.swing.GroupLayout searchResultsPanelLayout = new javax.swing.GroupLayout(searchResultsPanel);
        searchResultsPanel.setLayout(searchResultsPanelLayout);
        searchResultsPanelLayout.setHorizontalGroup(
            searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchResultsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchResultsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchResultPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstResultPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previousResultPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextResultPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastResultPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        searchResultsPanelLayout.setVerticalGroup(
            searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsPanelLayout.createSequentialGroup()
                .addComponent(searchResultsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastResultPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextResultPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previousResultPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstResultPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchResultPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        termDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Term detail"));
        termDetailPanel.setOpaque(false);

        ontologyNamespaceLabel.setText("Ontology namespace");

        ontologyNamespaceTextField.setEnabled(false);

        termLabelLabel.setText("Label");

        termLabelTextField.setEnabled(false);

        termDescriptionLabel.setText("Description");

        termAccessionLabel.setText("Accession");

        termAccessionTextField.setEnabled(false);

        termDescriptionTextArea.setEditable(false);
        termDescriptionTextArea.setColumns(20);
        termDescriptionTextArea.setLineWrap(true);
        termDescriptionTextArea.setRows(5);
        termDescriptionTextArea.setEnabled(false);
        jScrollPane1.setViewportView(termDescriptionTextArea);

        javax.swing.GroupLayout termDetailPanelLayout = new javax.swing.GroupLayout(termDetailPanel);
        termDetailPanel.setLayout(termDetailPanelLayout);
        termDetailPanelLayout.setHorizontalGroup(
            termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(termDetailPanelLayout.createSequentialGroup()
                .addGroup(termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, termDetailPanelLayout.createSequentialGroup()
                        .addGroup(termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, termDetailPanelLayout.createSequentialGroup()
                                .addComponent(ontologyNamespaceLabel)
                                .addGap(23, 23, 23))
                            .addGroup(termDetailPanelLayout.createSequentialGroup()
                                .addComponent(termAccessionLabel)
                                .addGap(92, 92, 92)))
                        .addGroup(termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ontologyNamespaceTextField)
                            .addComponent(termAccessionTextField)))
                    .addGroup(termDetailPanelLayout.createSequentialGroup()
                        .addGroup(termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(termLabelLabel)
                            .addComponent(termDescriptionLabel))
                        .addGap(84, 84, 84)
                        .addGroup(termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(termLabelTextField))))
                .addGap(6, 6, 6))
        );
        termDetailPanelLayout.setVerticalGroup(
            termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(termDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ontologyNamespaceLabel)
                    .addComponent(ontologyNamespaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(termAccessionLabel)
                    .addComponent(termAccessionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(termLabelLabel)
                    .addComponent(termLabelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(termDetailPanelLayout.createSequentialGroup()
                        .addComponent(termDescriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap())
        );

        closeButton.setText("close");
        closeButton.setMaximumSize(new java.awt.Dimension(80, 25));
        closeButton.setMinimumSize(new java.awt.Dimension(80, 25));
        closeButton.setPreferredSize(new java.awt.Dimension(80, 25));

        selectButton.setText("select");
        selectButton.setMaximumSize(new java.awt.Dimension(80, 25));
        selectButton.setMinimumSize(new java.awt.Dimension(80, 25));
        selectButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(termDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchResultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchInputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchInputTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInputLabel)
                    .addComponent(searchInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchResultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(termDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        olsTabbedPane.addTab("Search", searchPanel);

        searchSettingsPanel.setOpaque(false);

        searchOntologiesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ontologies"));
        searchOntologiesPanel.setOpaque(false);

        searchOntologiesLabel.setText("Search for terms in:");

        ontologiesSelectionButtonGroup.add(allOntologiesRadioButton);
        allOntologiesRadioButton.setText("all ontologies");

        ontologiesSelectionButtonGroup.add(preselectedOntologiesRadioButton);
        preselectedOntologiesRadioButton.setText("preselected ontologies");

        getAllOntologiesButton.setText("retrieve all");
        getAllOntologiesButton.setToolTipText("retrieve all available ontologies to make a selection");
        getAllOntologiesButton.setMaximumSize(new java.awt.Dimension(80, 25));
        getAllOntologiesButton.setMinimumSize(new java.awt.Dimension(80, 25));
        getAllOntologiesButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout searchOntologiesPanelLayout = new javax.swing.GroupLayout(searchOntologiesPanel);
        searchOntologiesPanel.setLayout(searchOntologiesPanelLayout);
        searchOntologiesPanelLayout.setHorizontalGroup(
            searchOntologiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchOntologiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchOntologiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchOntologiesPanelLayout.createSequentialGroup()
                        .addComponent(searchOntologiesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allOntologiesRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preselectedOntologiesRadioButton))
                    .addComponent(getAllOntologiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(233, Short.MAX_VALUE))
            .addComponent(ontologiesDualList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchOntologiesPanelLayout.setVerticalGroup(
            searchOntologiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchOntologiesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchOntologiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchOntologiesLabel)
                    .addComponent(allOntologiesRadioButton)
                    .addComponent(preselectedOntologiesRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ontologiesDualList, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getAllOntologiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        searchFieldsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search fields"));
        searchFieldsPanel.setOpaque(false);

        labelCheckBox.setText("label");

        synonymCheckBox.setText("synonym");

        descriptionCheckBox.setText("description");

        identifierCheckBox.setText("identifier");

        annotationPropertiesCheckBox.setText("annotation properties");

        searchFieldsLabel.setText("Search for terms using;");

        searchFieldsSelectionButtonGroup.add(defaultFieldsRadioButton);
        defaultFieldsRadioButton.setText("default fields");
        defaultFieldsRadioButton.setToolTipText("the default search fields are labels, synonyms, descriptions, identifiers and annotation properties");

        searchFieldsSelectionButtonGroup.add(customFieldsRadioButton);
        customFieldsRadioButton.setText("custom fields");
        customFieldsRadioButton.setToolTipText("");

        javax.swing.GroupLayout searchFieldsPanelLayout = new javax.swing.GroupLayout(searchFieldsPanel);
        searchFieldsPanel.setLayout(searchFieldsPanelLayout);
        searchFieldsPanelLayout.setHorizontalGroup(
            searchFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchFieldsPanelLayout.createSequentialGroup()
                .addGroup(searchFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCheckBox)
                    .addComponent(synonymCheckBox)
                    .addComponent(descriptionCheckBox)
                    .addComponent(identifierCheckBox)
                    .addComponent(annotationPropertiesCheckBox)
                    .addGroup(searchFieldsPanelLayout.createSequentialGroup()
                        .addComponent(searchFieldsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defaultFieldsRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customFieldsRadioButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        searchFieldsPanelLayout.setVerticalGroup(
            searchFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchFieldsPanelLayout.createSequentialGroup()
                .addGroup(searchFieldsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFieldsLabel)
                    .addComponent(defaultFieldsRadioButton)
                    .addComponent(customFieldsRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(synonymCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(identifierCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(annotationPropertiesCheckBox))
        );

        javax.swing.GroupLayout searchSettingsPanelLayout = new javax.swing.GroupLayout(searchSettingsPanel);
        searchSettingsPanel.setLayout(searchSettingsPanelLayout);
        searchSettingsPanelLayout.setHorizontalGroup(
            searchSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchFieldsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchOntologiesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        searchSettingsPanelLayout.setVerticalGroup(
            searchSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchOntologiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchFieldsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        olsTabbedPane.addTab("Search settings", searchSettingsPanel);

        javax.swing.GroupLayout olsParentPanelLayout = new javax.swing.GroupLayout(olsParentPanel);
        olsParentPanel.setLayout(olsParentPanelLayout);
        olsParentPanelLayout.setHorizontalGroup(
            olsParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(olsTabbedPane)
        );
        olsParentPanelLayout.setVerticalGroup(
            olsParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(olsTabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(olsParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(olsParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allOntologiesRadioButton;
    private javax.swing.JCheckBox annotationPropertiesCheckBox;
    private javax.swing.JButton closeButton;
    private javax.swing.JRadioButton customFieldsRadioButton;
    private javax.swing.JRadioButton defaultFieldsRadioButton;
    private javax.swing.JCheckBox descriptionCheckBox;
    private javax.swing.JButton firstResultPageButton;
    private javax.swing.JButton getAllOntologiesButton;
    private javax.swing.JCheckBox identifierCheckBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox labelCheckBox;
    private javax.swing.JButton lastResultPageButton;
    private javax.swing.JButton nextResultPageButton;
    private javax.swing.JPanel olsParentPanel;
    private javax.swing.JTabbedPane olsTabbedPane;
    private com.compomics.colims.client.compoment.DualList ontologiesDualList;
    private javax.swing.ButtonGroup ontologiesSelectionButtonGroup;
    private javax.swing.JLabel ontologyNamespaceLabel;
    private javax.swing.JTextField ontologyNamespaceTextField;
    private javax.swing.JRadioButton preselectedOntologiesRadioButton;
    private javax.swing.JButton previousResultPageButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchFieldsLabel;
    private javax.swing.JPanel searchFieldsPanel;
    private javax.swing.ButtonGroup searchFieldsSelectionButtonGroup;
    private javax.swing.JLabel searchInputLabel;
    private javax.swing.JTextField searchInputTextField;
    private javax.swing.JLabel searchOntologiesLabel;
    private javax.swing.JPanel searchOntologiesPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel searchResultPageLabel;
    private javax.swing.JTable searchResultTable;
    private javax.swing.JPanel searchResultsPanel;
    private javax.swing.JScrollPane searchResultsScrollPane;
    private javax.swing.JPanel searchSettingsPanel;
    private javax.swing.JButton selectButton;
    private javax.swing.JCheckBox synonymCheckBox;
    private javax.swing.JLabel termAccessionLabel;
    private javax.swing.JTextField termAccessionTextField;
    private javax.swing.JLabel termDescriptionLabel;
    private javax.swing.JTextArea termDescriptionTextArea;
    private javax.swing.JPanel termDetailPanel;
    private javax.swing.JLabel termLabelLabel;
    private javax.swing.JTextField termLabelTextField;
    // End of variables declaration//GEN-END:variables
}
