/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.colims.client.view.admin;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 *
 *
 * @author Niels Hulstaert
 */
public class OlsDialog extends javax.swing.JDialog {

    /**
     * Dialog constructor.
     *
     * @param parent the parent frame
     * @param modal the modal boolean
     */
    public OlsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ontologiesSelectionButtonGroup = new javax.swing.ButtonGroup();
        olsParentPanel = new javax.swing.JPanel();
        olsTabbedPane = new javax.swing.JTabbedPane();
        searchPanel = new javax.swing.JPanel();
        ontologyComboBox = new javax.swing.JComboBox<>();
        searchInputLabel = new javax.swing.JLabel();
        searchInputTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        searchResultsPanel = new javax.swing.JPanel();
        searchResultsScrollPane = new javax.swing.JScrollPane();
        searchResultsTable = new javax.swing.JTable();
        termDetailPanel = new javax.swing.JPanel();
        selectButton = new javax.swing.JButton();
        ontologiesLabel = new javax.swing.JLabel();
        searchSettingsPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        searchOntologiesLabel = new javax.swing.JLabel();
        allOntologiesRadioButton = new javax.swing.JRadioButton();
        preselectedOntologiesRadioButton = new javax.swing.JRadioButton();
        ontologiesDualList = new com.compomics.colims.client.compoment.DualList();
        getAllOntologiesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        olsParentPanel.setBackground(new java.awt.Color(255, 255, 255));

        olsTabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        searchPanel.setOpaque(false);

        searchInputLabel.setText("Search input:");

        searchButton.setText("search");
        searchButton.setMaximumSize(new java.awt.Dimension(80, 25));
        searchButton.setMinimumSize(new java.awt.Dimension(80, 25));
        searchButton.setPreferredSize(new java.awt.Dimension(80, 25));

        searchResultsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search results"));
        searchResultsPanel.setOpaque(false);

        searchResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        searchResultsScrollPane.setViewportView(searchResultsTable);

        javax.swing.GroupLayout searchResultsPanelLayout = new javax.swing.GroupLayout(searchResultsPanel);
        searchResultsPanel.setLayout(searchResultsPanelLayout);
        searchResultsPanelLayout.setHorizontalGroup(
            searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchResultsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchResultsPanelLayout.setVerticalGroup(
            searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsPanelLayout.createSequentialGroup()
                .addComponent(searchResultsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        termDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Term detail"));
        termDetailPanel.setOpaque(false);

        javax.swing.GroupLayout termDetailPanelLayout = new javax.swing.GroupLayout(termDetailPanel);
        termDetailPanel.setLayout(termDetailPanelLayout);
        termDetailPanelLayout.setHorizontalGroup(
            termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        termDetailPanelLayout.setVerticalGroup(
            termDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        selectButton.setText("select");
        selectButton.setMaximumSize(new java.awt.Dimension(80, 25));
        selectButton.setMinimumSize(new java.awt.Dimension(80, 25));
        selectButton.setPreferredSize(new java.awt.Dimension(80, 25));

        ontologiesLabel.setText("Ontologies:");

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchResultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(termDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ontologiesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ontologyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchInputTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ontologyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ontologiesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInputLabel)
                    .addComponent(searchInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchResultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(termDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        olsTabbedPane.addTab("Search", searchPanel);

        searchSettingsPanel.setOpaque(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ontologies"));
        jPanel1.setOpaque(false);

        searchOntologiesLabel.setText("Search for terms in:");

        ontologiesSelectionButtonGroup.add(allOntologiesRadioButton);
        allOntologiesRadioButton.setText("all ontologies");

        ontologiesSelectionButtonGroup.add(preselectedOntologiesRadioButton);
        preselectedOntologiesRadioButton.setText("preselected ontologies");

        getAllOntologiesButton.setText("retrieve all");
        getAllOntologiesButton.setToolTipText("retrieve all available ontologies");
        getAllOntologiesButton.setMaximumSize(new java.awt.Dimension(80, 25));
        getAllOntologiesButton.setMinimumSize(new java.awt.Dimension(80, 25));
        getAllOntologiesButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ontologiesDualList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchOntologiesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(allOntologiesRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preselectedOntologiesRadioButton))
                            .addComponent(getAllOntologiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 215, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchOntologiesLabel)
                    .addComponent(allOntologiesRadioButton)
                    .addComponent(preselectedOntologiesRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ontologiesDualList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getAllOntologiesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout searchSettingsPanelLayout = new javax.swing.GroupLayout(searchSettingsPanel);
        searchSettingsPanel.setLayout(searchSettingsPanelLayout);
        searchSettingsPanelLayout.setHorizontalGroup(
            searchSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchSettingsPanelLayout.setVerticalGroup(
            searchSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        olsTabbedPane.addTab("Search settings", searchSettingsPanel);

        javax.swing.GroupLayout olsParentPanelLayout = new javax.swing.GroupLayout(olsParentPanel);
        olsParentPanel.setLayout(olsParentPanelLayout);
        olsParentPanelLayout.setHorizontalGroup(
            olsParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(olsParentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(olsTabbedPane)
                .addContainerGap())
        );
        olsParentPanelLayout.setVerticalGroup(
            olsParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(olsParentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(olsTabbedPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(olsParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(olsParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allOntologiesRadioButton;
    private javax.swing.JButton getAllOntologiesButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel olsParentPanel;
    private javax.swing.JTabbedPane olsTabbedPane;
    private com.compomics.colims.client.compoment.DualList ontologiesDualList;
    private javax.swing.JLabel ontologiesLabel;
    private javax.swing.ButtonGroup ontologiesSelectionButtonGroup;
    private javax.swing.JComboBox<String> ontologyComboBox;
    private javax.swing.JRadioButton preselectedOntologiesRadioButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchInputLabel;
    private javax.swing.JTextField searchInputTextField;
    private javax.swing.JLabel searchOntologiesLabel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel searchResultsPanel;
    private javax.swing.JScrollPane searchResultsScrollPane;
    private javax.swing.JTable searchResultsTable;
    private javax.swing.JPanel searchSettingsPanel;
    private javax.swing.JButton selectButton;
    private javax.swing.JPanel termDetailPanel;
    // End of variables declaration//GEN-END:variables
}
