package com.compomics.colims.client.view.admin;

import com.compomics.colims.client.compoment.DualList;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author niels
 */
public class UserManagementDialog extends javax.swing.JDialog {

    /**
     * Creates new form UserManagementDialog
     */
    public UserManagementDialog(Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        setLocationRelativeTo(parent);
    }

    public JButton getAddUserButton() {
        return addUserButton;
    }

    public JButton getDeleteUserButton() {
        return deleteUserButton;
    }

    public JTextField getEmailTextField() {
        return emailTextField;
    }

    public JTextField getFirstNameTextField() {
        return firstNameTextField;
    }

    public JPanel getGroupCrudPanel() {
        return groupCrudPanel;
    }

    public JTextArea getGroupDescriptionTextArea() {
        return groupDescriptionTextArea;
    }

    public DualList getGroupDualList() {
        return groupDualList;
    }

    public JTextField getGroupNameTextField() {
        return groupNameTextField;
    }

    public JButton getGroupSaveOrUpdateButton() {
        return groupSaveOrUpdateButton;
    }

    public JLabel getGroupStateInfoLabel() {
        return groupStateInfoLabel;
    }

    public JTextField getLastNameTextField() {
        return lastNameTextField;
    }

    public JPasswordField getPasswordTextField() {
        return passwordTextField;
    }

    public DualList getRoleDualList() {
        return roleDualList;
    }

    public JPanel getUserCrudPanel() {
        return userCrudPanel;
    }

    public JList getUserList() {
        return userList;
    }

    public JTextField getUserNameTextField() {
        return userNameTextField;
    }

    public JButton getUserSaveOrUpdateButton() {
        return userSaveOrUpdateButton;
    }

    public JLabel getUserStateInfoLabel() {
        return userStateInfoLabel;
    }

    public JList getGroupList() {
        return groupList;
    }

    public JButton getAddGroupButton() {
        return addGroupButton;
    }

    public JButton getAddPermissionButton() {
        return addPermissionButton;
    }

    public JButton getAddRoleButton() {
        return addRoleButton;
    }

    public JButton getDeleteGroupButton() {
        return deleteGroupButton;
    }

    public JButton getDeletePermissionButton() {
        return deletePermissionButton;
    }

    public JButton getDeleteRoleButton() {
        return deleteRoleButton;
    }

    public JTextField getPermissionNameTextField() {
        return permissionNameTextField;
    }

    public JButton getPermissionSaveOrUpdateButton() {
        return permissionSaveOrUpdateButton;
    }

    public JLabel getPermissionStateInfoLabel() {
        return permissionStateInfoLabel;
    }

    public JTextField getRoleNameTextField() {
        return roleNameTextField;
    }

    public JButton getRoleSaveOrUpdateButton() {
        return roleSaveOrUpdateButton;
    }

    public JLabel getRoleStateInfoLabel() {
        return roleStateInfoLabel;
    }

    public DualList getPermissionDualList() {
        return permissionDualList;
    }

    public JList getPermissionList() {
        return permissionList;
    }

    public JList getRoleList() {
        return roleList;
    }

    public JTextArea getRoleDescriptionTextArea() {
        return roleDescriptionTextArea;
    }

    public JTextArea getPermissionDescriptionTextArea() {
        return permissionDescriptionTextArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userManagementTabbedPane = new javax.swing.JTabbedPane();
        userCrudPanel = new javax.swing.JPanel();
        userOverviewPanel = new javax.swing.JPanel();
        userListScrollPane = new javax.swing.JScrollPane();
        userList = new javax.swing.JList();
        addUserButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        userDetailPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        userSaveOrUpdateButton = new javax.swing.JButton();
        userStateInfoLabel = new javax.swing.JLabel();
        groupDualList = new com.compomics.colims.client.compoment.DualList();
        groupsLabel = new javax.swing.JLabel();
        groupCrudPanel = new javax.swing.JPanel();
        groupOverviewPanel = new javax.swing.JPanel();
        groupListScrollPane = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList();
        addGroupButton = new javax.swing.JButton();
        deleteGroupButton = new javax.swing.JButton();
        groupDetailPanel = new javax.swing.JPanel();
        groupDescriptionLabel = new javax.swing.JLabel();
        groupNameLabel = new javax.swing.JLabel();
        groupNameTextField = new javax.swing.JTextField();
        groupSaveOrUpdateButton = new javax.swing.JButton();
        groupStateInfoLabel = new javax.swing.JLabel();
        groupDescriptionScrollPane = new javax.swing.JScrollPane();
        groupDescriptionTextArea = new javax.swing.JTextArea();
        roleDualList = new com.compomics.colims.client.compoment.DualList();
        rolesLabel = new javax.swing.JLabel();
        roleCrudPanel = new javax.swing.JPanel();
        roleOverviewPanel = new javax.swing.JPanel();
        roleListScrollPane = new javax.swing.JScrollPane();
        roleList = new javax.swing.JList();
        addRoleButton = new javax.swing.JButton();
        deleteRoleButton = new javax.swing.JButton();
        roleDetailPanel = new javax.swing.JPanel();
        roleDescriptionLabel = new javax.swing.JLabel();
        roleNameLabel = new javax.swing.JLabel();
        roleNameTextField = new javax.swing.JTextField();
        roleSaveOrUpdateButton = new javax.swing.JButton();
        roleStateInfoLabel = new javax.swing.JLabel();
        roleDescriptionScrollPane = new javax.swing.JScrollPane();
        roleDescriptionTextArea = new javax.swing.JTextArea();
        permissionDualList = new com.compomics.colims.client.compoment.DualList();
        permissionsLabel = new javax.swing.JLabel();
        permissionCrudPanel = new javax.swing.JPanel();
        permissionOverviewPanel = new javax.swing.JPanel();
        permissionListScrollPane = new javax.swing.JScrollPane();
        permissionList = new javax.swing.JList();
        addPermissionButton = new javax.swing.JButton();
        deletePermissionButton = new javax.swing.JButton();
        permissionDetailPanel = new javax.swing.JPanel();
        permissionDescriptionLabel = new javax.swing.JLabel();
        permissionNameLabel = new javax.swing.JLabel();
        permissionNameTextField = new javax.swing.JTextField();
        permissionSaveOrUpdateButton = new javax.swing.JButton();
        permissionStateInfoLabel = new javax.swing.JLabel();
        permissionDescriptionScrollPane = new javax.swing.JScrollPane();
        permissionDescriptionTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("user management");
        setModal(true);
        setResizable(false);

        userManagementTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        userManagementTabbedPane.setOpaque(true);

        userCrudPanel.setOpaque(false);

        userOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("overview"));
        userOverviewPanel.setOpaque(false);
        userOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        userListScrollPane.setViewportView(userList);

        addUserButton.setText("add");
        addUserButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addUserButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addUserButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deleteUserButton.setText("delete");
        deleteUserButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteUserButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteUserButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout userOverviewPanelLayout = new javax.swing.GroupLayout(userOverviewPanel);
        userOverviewPanel.setLayout(userOverviewPanelLayout);
        userOverviewPanelLayout.setHorizontalGroup(
            userOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(userOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userOverviewPanelLayout.setVerticalGroup(
            userOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap())
        );

        userDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("detail"));
        userDetailPanel.setOpaque(false);
        userDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        firstNameLabel.setText("first name");

        lastNameLabel.setText("last name");

        emailLabel.setText("email");

        passwordLabel.setText("password");

        userNameLabel.setText("user name");
        userNameLabel.setPreferredSize(new java.awt.Dimension(48, 14));

        userSaveOrUpdateButton.setText("save");
        userSaveOrUpdateButton.setMaximumSize(new java.awt.Dimension(80, 25));
        userSaveOrUpdateButton.setMinimumSize(new java.awt.Dimension(80, 25));
        userSaveOrUpdateButton.setPreferredSize(new java.awt.Dimension(80, 25));

        userStateInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userStateInfoLabel.setForeground(new java.awt.Color(255, 0, 0));
        userStateInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        userStateInfoLabel.setMaximumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel.setPreferredSize(new java.awt.Dimension(100, 20));

        groupsLabel.setText("group(s)");

        javax.swing.GroupLayout userDetailPanelLayout = new javax.swing.GroupLayout(userDetailPanel);
        userDetailPanel.setLayout(userDetailPanelLayout);
        userDetailPanelLayout.setHorizontalGroup(
            userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userDetailPanelLayout.createSequentialGroup()
                        .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(userDetailPanelLayout.createSequentialGroup()
                                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(userDetailPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                                .addComponent(lastNameTextField)
                                                .addComponent(passwordTextField))
                                            .addComponent(firstNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(userStateInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userDetailPanelLayout.createSequentialGroup()
                                .addComponent(groupsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(groupDualList, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(userSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        userDetailPanelLayout.setVerticalGroup(
            userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupsLabel)
                    .addComponent(userStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupDualList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(userDetailPanelLayout.createSequentialGroup()
                        .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordLabel)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout userCrudPanelLayout = new javax.swing.GroupLayout(userCrudPanel);
        userCrudPanel.setLayout(userCrudPanelLayout);
        userCrudPanelLayout.setHorizontalGroup(
            userCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userOverviewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
            .addComponent(userDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        userCrudPanelLayout.setVerticalGroup(
            userCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userCrudPanelLayout.createSequentialGroup()
                .addComponent(userOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userManagementTabbedPane.addTab("Users", userCrudPanel);

        groupCrudPanel.setOpaque(false);

        groupOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("overview"));
        groupOverviewPanel.setOpaque(false);
        groupOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        groupListScrollPane.setViewportView(groupList);

        addGroupButton.setText("add");
        addGroupButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addGroupButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addGroupButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deleteGroupButton.setText("delete");
        deleteGroupButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteGroupButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteGroupButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout groupOverviewPanelLayout = new javax.swing.GroupLayout(groupOverviewPanel);
        groupOverviewPanel.setLayout(groupOverviewPanelLayout);
        groupOverviewPanelLayout.setHorizontalGroup(
            groupOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(groupOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        groupOverviewPanelLayout.setVerticalGroup(
            groupOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groupOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(groupListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap())
        );

        groupDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("detail"));
        groupDetailPanel.setOpaque(false);
        groupDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        groupDescriptionLabel.setText("description");

        groupNameLabel.setText("name");
        groupNameLabel.setPreferredSize(new java.awt.Dimension(48, 14));

        groupSaveOrUpdateButton.setText("save");
        groupSaveOrUpdateButton.setMaximumSize(new java.awt.Dimension(80, 25));
        groupSaveOrUpdateButton.setMinimumSize(new java.awt.Dimension(80, 25));
        groupSaveOrUpdateButton.setPreferredSize(new java.awt.Dimension(80, 25));

        groupStateInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        groupStateInfoLabel.setForeground(new java.awt.Color(255, 0, 0));
        groupStateInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        groupStateInfoLabel.setMaximumSize(new java.awt.Dimension(100, 20));
        groupStateInfoLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        groupStateInfoLabel.setPreferredSize(new java.awt.Dimension(100, 20));

        groupDescriptionTextArea.setColumns(20);
        groupDescriptionTextArea.setLineWrap(true);
        groupDescriptionTextArea.setRows(5);
        groupDescriptionScrollPane.setViewportView(groupDescriptionTextArea);

        rolesLabel.setText("role(s)");

        javax.swing.GroupLayout groupDetailPanelLayout = new javax.swing.GroupLayout(groupDetailPanel);
        groupDetailPanel.setLayout(groupDetailPanelLayout);
        groupDetailPanelLayout.setHorizontalGroup(
            groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groupDetailPanelLayout.createSequentialGroup()
                        .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(groupDetailPanelLayout.createSequentialGroup()
                                .addComponent(groupNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(groupNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(groupDetailPanelLayout.createSequentialGroup()
                                .addComponent(groupDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(groupDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(roleDualList, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(groupDetailPanelLayout.createSequentialGroup()
                        .addComponent(groupStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rolesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(groupSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        groupDetailPanelLayout.setVerticalGroup(
            groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupDetailPanelLayout.createSequentialGroup()
                .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groupDetailPanelLayout.createSequentialGroup()
                        .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(groupNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(groupNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(groupDescriptionLabel)
                            .addComponent(groupDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(roleDualList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout groupCrudPanelLayout = new javax.swing.GroupLayout(groupCrudPanel);
        groupCrudPanel.setLayout(groupCrudPanelLayout);
        groupCrudPanelLayout.setHorizontalGroup(
            groupCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupOverviewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
            .addComponent(groupDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        groupCrudPanelLayout.setVerticalGroup(
            groupCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupCrudPanelLayout.createSequentialGroup()
                .addComponent(groupOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userManagementTabbedPane.addTab("Groups", groupCrudPanel);

        roleCrudPanel.setOpaque(false);

        roleOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("overview"));
        roleOverviewPanel.setOpaque(false);
        roleOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        roleListScrollPane.setViewportView(roleList);

        addRoleButton.setText("add");
        addRoleButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addRoleButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addRoleButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deleteRoleButton.setText("delete");
        deleteRoleButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteRoleButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteRoleButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout roleOverviewPanelLayout = new javax.swing.GroupLayout(roleOverviewPanel);
        roleOverviewPanel.setLayout(roleOverviewPanelLayout);
        roleOverviewPanelLayout.setHorizontalGroup(
            roleOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roleListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(roleOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteRoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roleOverviewPanelLayout.setVerticalGroup(
            roleOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roleOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roleOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addRoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteRoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(roleListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap())
        );

        roleDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("detail"));
        roleDetailPanel.setOpaque(false);
        roleDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        roleDescriptionLabel.setText("description");

        roleNameLabel.setText("name");
        roleNameLabel.setPreferredSize(new java.awt.Dimension(48, 14));

        roleSaveOrUpdateButton.setText("save");
        roleSaveOrUpdateButton.setMaximumSize(new java.awt.Dimension(80, 25));
        roleSaveOrUpdateButton.setMinimumSize(new java.awt.Dimension(80, 25));
        roleSaveOrUpdateButton.setPreferredSize(new java.awt.Dimension(80, 25));

        roleStateInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        roleStateInfoLabel.setForeground(new java.awt.Color(255, 0, 0));
        roleStateInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        roleStateInfoLabel.setMaximumSize(new java.awt.Dimension(100, 20));
        roleStateInfoLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        roleStateInfoLabel.setPreferredSize(new java.awt.Dimension(100, 20));

        roleDescriptionTextArea.setColumns(20);
        roleDescriptionTextArea.setLineWrap(true);
        roleDescriptionTextArea.setRows(5);
        roleDescriptionScrollPane.setViewportView(roleDescriptionTextArea);

        permissionsLabel.setText("permission(s)");

        javax.swing.GroupLayout roleDetailPanelLayout = new javax.swing.GroupLayout(roleDetailPanel);
        roleDetailPanel.setLayout(roleDetailPanelLayout);
        roleDetailPanelLayout.setHorizontalGroup(
            roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roleDetailPanelLayout.createSequentialGroup()
                        .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(roleDetailPanelLayout.createSequentialGroup()
                                .addComponent(roleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(roleDetailPanelLayout.createSequentialGroup()
                                .addComponent(roleDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(roleDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(permissionDualList, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roleDetailPanelLayout.createSequentialGroup()
                        .addComponent(roleStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(permissionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roleDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roleSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roleDetailPanelLayout.setVerticalGroup(
            roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleDetailPanelLayout.createSequentialGroup()
                .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roleStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permissionsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roleDetailPanelLayout.createSequentialGroup()
                        .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roleDescriptionLabel)
                            .addComponent(roleDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(permissionDualList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout roleCrudPanelLayout = new javax.swing.GroupLayout(roleCrudPanel);
        roleCrudPanel.setLayout(roleCrudPanelLayout);
        roleCrudPanelLayout.setHorizontalGroup(
            roleCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roleOverviewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
            .addComponent(roleDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        roleCrudPanelLayout.setVerticalGroup(
            roleCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roleCrudPanelLayout.createSequentialGroup()
                .addComponent(roleOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userManagementTabbedPane.addTab("Roles", roleCrudPanel);

        permissionCrudPanel.setOpaque(false);

        permissionOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("overview"));
        permissionOverviewPanel.setOpaque(false);
        permissionOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        permissionListScrollPane.setOpaque(false);

        permissionListScrollPane.setViewportView(permissionList);

        addPermissionButton.setText("add");
        addPermissionButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addPermissionButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addPermissionButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deletePermissionButton.setText("delete");
        deletePermissionButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deletePermissionButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deletePermissionButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout permissionOverviewPanelLayout = new javax.swing.GroupLayout(permissionOverviewPanel);
        permissionOverviewPanel.setLayout(permissionOverviewPanelLayout);
        permissionOverviewPanelLayout.setHorizontalGroup(
            permissionOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(permissionListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(permissionOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletePermissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPermissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        permissionOverviewPanelLayout.setVerticalGroup(
            permissionOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permissionOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(permissionOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addPermissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletePermissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(permissionListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap())
        );

        permissionDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("detail"));
        permissionDetailPanel.setOpaque(false);
        permissionDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        permissionDescriptionLabel.setText("description");

        permissionNameLabel.setText("name");
        permissionNameLabel.setPreferredSize(new java.awt.Dimension(48, 14));

        permissionSaveOrUpdateButton.setText("save");
        permissionSaveOrUpdateButton.setMaximumSize(new java.awt.Dimension(80, 25));
        permissionSaveOrUpdateButton.setMinimumSize(new java.awt.Dimension(80, 25));
        permissionSaveOrUpdateButton.setPreferredSize(new java.awt.Dimension(80, 25));

        permissionStateInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        permissionStateInfoLabel.setForeground(new java.awt.Color(255, 0, 0));
        permissionStateInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        permissionStateInfoLabel.setMaximumSize(new java.awt.Dimension(100, 20));
        permissionStateInfoLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        permissionStateInfoLabel.setPreferredSize(new java.awt.Dimension(100, 20));

        permissionDescriptionTextArea.setColumns(20);
        permissionDescriptionTextArea.setLineWrap(true);
        permissionDescriptionTextArea.setRows(5);
        permissionDescriptionScrollPane.setViewportView(permissionDescriptionTextArea);

        javax.swing.GroupLayout permissionDetailPanelLayout = new javax.swing.GroupLayout(permissionDetailPanel);
        permissionDetailPanel.setLayout(permissionDetailPanelLayout);
        permissionDetailPanelLayout.setHorizontalGroup(
            permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(permissionDetailPanelLayout.createSequentialGroup()
                        .addComponent(permissionNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(permissionNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(permissionDetailPanelLayout.createSequentialGroup()
                        .addComponent(permissionDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(permissionDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(permissionStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(496, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, permissionDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(permissionSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        permissionDetailPanelLayout.setVerticalGroup(
            permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionDetailPanelLayout.createSequentialGroup()
                .addComponent(permissionStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permissionNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permissionNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(permissionDescriptionLabel)
                    .addComponent(permissionDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(permissionSaveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout permissionCrudPanelLayout = new javax.swing.GroupLayout(permissionCrudPanel);
        permissionCrudPanel.setLayout(permissionCrudPanelLayout);
        permissionCrudPanelLayout.setHorizontalGroup(
            permissionCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(permissionOverviewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
            .addComponent(permissionDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        permissionCrudPanelLayout.setVerticalGroup(
            permissionCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, permissionCrudPanelLayout.createSequentialGroup()
                .addComponent(permissionOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permissionDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userManagementTabbedPane.addTab("Permissions", permissionCrudPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userManagementTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userManagementTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroupButton;
    private javax.swing.JButton addPermissionButton;
    private javax.swing.JButton addRoleButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton deleteGroupButton;
    private javax.swing.JButton deletePermissionButton;
    private javax.swing.JButton deleteRoleButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel groupCrudPanel;
    private javax.swing.JLabel groupDescriptionLabel;
    private javax.swing.JScrollPane groupDescriptionScrollPane;
    private javax.swing.JTextArea groupDescriptionTextArea;
    private javax.swing.JPanel groupDetailPanel;
    private com.compomics.colims.client.compoment.DualList groupDualList;
    private javax.swing.JList groupList;
    private javax.swing.JScrollPane groupListScrollPane;
    private javax.swing.JLabel groupNameLabel;
    private javax.swing.JTextField groupNameTextField;
    private javax.swing.JPanel groupOverviewPanel;
    private javax.swing.JButton groupSaveOrUpdateButton;
    private javax.swing.JLabel groupStateInfoLabel;
    private javax.swing.JLabel groupsLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPanel permissionCrudPanel;
    private javax.swing.JLabel permissionDescriptionLabel;
    private javax.swing.JScrollPane permissionDescriptionScrollPane;
    private javax.swing.JTextArea permissionDescriptionTextArea;
    private javax.swing.JPanel permissionDetailPanel;
    private com.compomics.colims.client.compoment.DualList permissionDualList;
    private javax.swing.JList permissionList;
    private javax.swing.JScrollPane permissionListScrollPane;
    private javax.swing.JLabel permissionNameLabel;
    private javax.swing.JTextField permissionNameTextField;
    private javax.swing.JPanel permissionOverviewPanel;
    private javax.swing.JButton permissionSaveOrUpdateButton;
    private javax.swing.JLabel permissionStateInfoLabel;
    private javax.swing.JLabel permissionsLabel;
    private javax.swing.JPanel roleCrudPanel;
    private javax.swing.JLabel roleDescriptionLabel;
    private javax.swing.JScrollPane roleDescriptionScrollPane;
    private javax.swing.JTextArea roleDescriptionTextArea;
    private javax.swing.JPanel roleDetailPanel;
    private com.compomics.colims.client.compoment.DualList roleDualList;
    private javax.swing.JList roleList;
    private javax.swing.JScrollPane roleListScrollPane;
    private javax.swing.JLabel roleNameLabel;
    private javax.swing.JTextField roleNameTextField;
    private javax.swing.JPanel roleOverviewPanel;
    private javax.swing.JButton roleSaveOrUpdateButton;
    private javax.swing.JLabel roleStateInfoLabel;
    private javax.swing.JLabel rolesLabel;
    private javax.swing.JPanel userCrudPanel;
    private javax.swing.JPanel userDetailPanel;
    private javax.swing.JList userList;
    private javax.swing.JScrollPane userListScrollPane;
    private javax.swing.JTabbedPane userManagementTabbedPane;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JPanel userOverviewPanel;
    private javax.swing.JButton userSaveOrUpdateButton;
    private javax.swing.JLabel userStateInfoLabel;
    // End of variables declaration//GEN-END:variables
}
