package com.compomics.colims.distributed.io.maxquant.headers;

/**
 * Created by Iain on 03/12/2014.
 */
public class MaxQuantSummaryHeaders {

    public enum HEADERS {
        AV_ABSOLUTE_MASS_DEVIATION,
        ENZYME,
        FIXED_MODIFICATIONS,
        INSTRUMENT,
        ISOTOPE_PATTERNS,
        ISOTOPE_PATTERNS_SEQUENCED,
        ISOTOPE_PATTERNS_SEQUENCED_PERCENTAGE,
        ISOTOPE_PATTERNS_SEQUENCED_Z_1,
        ISOTOPE_PATTERNS_SEQUENCED_Z_1_PERCENTAGE,
        ISOTOPE_PATTERNS_REPEATEDLY_SEQUENCED,
        ISOTOPE_PATTERNS_REPEATEDLY_SEQUENCED_PERCENTAGE,
        LABEL_FREE_INTENSITY_NORM_PARAM,
        LABELS0,
        LC_MS_RUN_TYPE,
        MASS_STANDARD_DEVIATION,
        MAX_MISSED_CLEAVAGES,
        MS,
        MS_MS,
        MS_MS_IDENTIFIED,
        MS_MS_IDENTIFIED_ISO,
        MS_MS_IDENTIFIED_ISO_PERCENTAGE,
        MS_MS_IDENTIFIED_PEAK,
        MS_MS_IDENTIFIED_PEAK_PERCENTAGE,
        MS_MS_IDENTIFIED_PERCENTAGE,
        MS_MS_IDENTIFIED_SIL,
        MS_MS_IDENTIFIED_SIL_PERCENTAGE,
        MS_MS_ON_POLYMERS,
        MS_MS_SUBMITTED,
        MS_MS_SUBMITTED_ISO,
        MS_MS_SUBMITTED_PEAK,
        MS_MS_SUBMITTED_SIL,
        MULTIPLICITY,
        PEAKS,
        PEAKS_REPEATEDLY_SEQUENCED,
        PEAKS_REPEATEDLY_SEQUENCED_PERCENTAGE,
        PEAKS_SEQUENCED,
        PEAKS_SEQUENCED_PERCENTAGE,
        PEPTIDE_SEQUENCES_IDENTIFIED,
        PROTEASE,
        PROTEASE_FIRST_SEARCH,
        RAW_FILE,
        RECALIBRATED,
        TIME_DEPENDENT_CALIBRATION,
        TUNE_FILE,
        USE_PROTEASE_FIRST_SEARCH,
        USE_VARIABLE_MODIFICATIONS_FIRST_SEARCH,
        VARIABLE_MODIFICATIONS,
        VARIABLE_MODIFICATIONS_FIRST_SEARCH
    }
}
