package com.compomics.colims.distributed.io.maxquant.headers;

/**
 * Created by Iain on 03/12/2014.
 */
public class MaxQuantMSMSHeaders {

    public enum HEADERS {
        ACETYL_PROTEIN_N_TERM,
        BASE_PEAK_FRACTION,
        CHARGE,
        COMBINATORICS,
        DELTA_SCORE,
        EVIDENCE_ID,
        FRACTION_OF_TOTAL_SPECTRUM,
        FRAGMENTATION,
        GENE_NAMES,
        ID,
        INTENSITIES,
        INTENSITY_COVERAGE,
        ISOTOPE_INDEX,
        LENGTH,
        M_Z,
        MASS,
        MASSES,
        MASS_ANALYZER,
        MASS_DEVIATIONS_DA,
        MASS_DEVIATIONS_PPM,
        MASS_ERROR_PPM,
        MATCHES,
        MISSED_CLEAVAGES,
        MOD_PEPTIDE_ID,
        MODIFICATIONS,
        MODIFIED_SEQUENCE,
        NEUTRAL_LOSS_LEVEL,
        NUMBER_OF_MATCHES,
        OXIDATION_M,
        OXIDATION_M_PROBABILITIES,
        OXIDATION_M_SCORE_DIFFS,
        OXIDATION_M_SITE_IDS,
        PEAK_COVERAGE,
        PEP,
        PEPTIDE_ID,
        PIF,
        PRECURSOR,
        PRECURSOR_APEX_FRACTION,
        PRECURSOR_APEX_OFFSET,
        PRECURSOR_FULL_SCANNUMBER,
        PRECURSOR_INTENSITY,
        PROTEINS,
        PROTEIN_GROUP_IDS,
        PROTEIN_NAMES,
        RAW_FILE,
        RETENTION_TIME,
        REVERSE,
        SCAN_EVENT_NUMBER,
        SCAN_INDEX,
        SCAN_TYPE,
        SCAN_NUMBER,
        SCORE,
        SEQUENCE,
        SIMPLE_MASS_ERROR_PPM,
        TYPE,
        UNIPROT
    }
}
