package com.compomics.colims.client.view;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Niels Hulstaert
 */
public class ExperimentBinaryFileDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoginDialog
     */
    public ExperimentBinaryFileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

        samplesTableScrollPane.getViewport().setOpaque(false);
        samplesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    public JButton getAttachmentsEditButton() {
        return attachmentsEditButton;
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public JTextArea getDescriptionTextArea() {
        return descriptionTextArea;
    }

    public JTextField getAttachementsTextField() {
        return attachementsTextField;
    }

    public JTextField getNumberTextField() {
        return numberTextField;
    }

    public JButton getSaveOrUpdateButton() {
        return saveOrUpdateButton;
    }

    public JTextField getStorageLocationTextField() {
        return storageLocationTextField;
    }

    public JTextField getTitleTextField() {
        return titleTextField;
    }

    public JButton getAddSampleButton() {
        return addSampleButton;
    }

    public JButton getDeleteSampleButton() {
        return deleteSampleButton;
    }

    public JButton getEditSampleButton() {
        return editSampleButton;
    }

    public JTable getSamplesTable() {
        return samplesTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("experiment metadata management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
