package com.compomics.colims.client.view;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.border.EmptyBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author Niels Hulstaert
 */
public class PeptideShakerDataImportPanel extends javax.swing.JPanel {

    private final JFileChooser cpsFileChooser = new JFileChooser();
    private final JFileChooser mgfFileChooser = new JFileChooser();
    private final JFileChooser fastaFileChooser = new JFileChooser();    

    /**
     * Creates new form PeptideShakerDataImportPanel
     */
    public PeptideShakerDataImportPanel() {
        initComponents();
        
        cpsFileLabel.setBorder(BorderFactory.createCompoundBorder(new LineBorder(new Color(240, 240, 240)), new EmptyBorder(0, 5, 0, 0)));
        fastaFileLabel.setBorder(BorderFactory.createCompoundBorder(new LineBorder(new Color(240, 240, 240)), new EmptyBorder(0, 5, 0, 0)));
        
        mgfFilesScrollPane.getViewport().setOpaque(false);
    }  

    public JFileChooser getCpsFileChooser() {
        return cpsFileChooser;
    }

    public JFileChooser getMgfFileChooser() {
        return mgfFileChooser;
    }

    public JFileChooser getFastaFileChooser() {
        return fastaFileChooser;
    }

    public JButton getAddMgfButton() {
        return addMgfButton;
    }

    public JLabel getCpsFileLabel() {
        return cpsFileLabel;
    }

    public JLabel getFastaFileLabel() {
        return fastaFileLabel;
    }

    public JList getMgfFileList() {
        return mgfFileList;
    }

    public JButton getRemoveMgfButton() {
        return removeMgfButton;
    }

    public JButton getSelectCpsButton() {
        return selectCpsButton;
    }

    public JButton getSelectFastaButton() {
        return selectFastaButton;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cpsFileSelectionLabel = new javax.swing.JLabel();
        cpsFileLabel = new javax.swing.JLabel();
        fastaFileLabel = new javax.swing.JLabel();
        selectCpsButton = new javax.swing.JButton();
        selectFastaButton = new javax.swing.JButton();
        fileSelectionLabel1 = new javax.swing.JLabel();
        mgfFilesScrollPane = new javax.swing.JScrollPane();
        mgfFileList = new javax.swing.JList();
        addMgfButton = new javax.swing.JButton();
        removeMgfButton = new javax.swing.JButton();
        fastaFileSelectionLabel = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();

        setOpaque(false);

        cpsFileSelectionLabel.setText("Select a PeptideShaker cps file");

        selectCpsButton.setText("browse");

        selectFastaButton.setText("browse");

        fileSelectionLabel1.setText("Select MGF file(s)");

        mgfFilesScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        mgfFilesScrollPane.setViewportView(mgfFileList);

        addMgfButton.setText("add");

        removeMgfButton.setText("remove");

        fastaFileSelectionLabel.setText("Select a FASTA file");

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpsFileSelectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpsFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectCpsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fastaFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectFastaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fastaFileSelectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mgfFilesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addMgfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeMgfButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fileSelectionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpsFileSelectionLabel)
                            .addComponent(fileSelectionLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mgfFilesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addMgfButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(removeMgfButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cpsFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selectCpsButton))
                                        .addGap(18, 18, 18)
                                        .addComponent(fastaFileSelectionLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fastaFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selectFastaButton))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(separator))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMgfButton;
    private javax.swing.JLabel cpsFileLabel;
    private javax.swing.JLabel cpsFileSelectionLabel;
    private javax.swing.JLabel fastaFileLabel;
    private javax.swing.JLabel fastaFileSelectionLabel;
    private javax.swing.JLabel fileSelectionLabel1;
    private javax.swing.JList mgfFileList;
    private javax.swing.JScrollPane mgfFilesScrollPane;
    private javax.swing.JButton removeMgfButton;
    private javax.swing.JButton selectCpsButton;
    private javax.swing.JButton selectFastaButton;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
