package com.compomics.colims.client.view;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author Niels Hulstaert
 */
public class TaskMonitoringDialog extends javax.swing.JDialog {

    /**
     * Dialog constructor
     *
     * @param parent the parent frame
     * @param modal the modal boolean
     */
    public TaskMonitoringDialog(final Frame parent, final boolean modal) {
        super(parent, modal);

        initComponents();

        taskQueueScrollPane.getViewport().setOpaque(false);
        taskErrorQueueScrollPane.getViewport().setOpaque(false);
        completedTaskQueueScrollPane.getViewport().setOpaque(false);
        this.getContentPane().setBackground(Color.WHITE);
    }

    public JTable getTaskQueueTable() {
        return taskQueueTable;
    }

    public JTable getTaskErrorQueueTable() {
        return taskErrorQueueTable;
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public JButton getRefreshButton() {
        return refreshButton;
    }

    public JTable getCompletedTaskQueueTable() {
        return completedTaskQueueTable;
    }

    public JTextArea getErrorDetailTextArea() {
        return errorDetailTextArea;
    }        

    public JButton getDeleteTaskErrorButton() {
        return deleteTaskErrorButton;
    }

    public JButton getResendTaskErrorButton() {
        return resendTaskErrorButton;
    }   

    public JButton getDeleteDbTaskButton() {
        return deleteDbTaskButton;
    }

    public JButton getPurgeTaskErrorsButton() {
        return purgeTaskErrorsButton;
    }

    public JButton getDeleteCompletedTaskButton() {
        return deleteCompletedTaskButton;
    }

    public JButton getPurgeCompletedTasksButton() {
        return purgeCompletedTasksButton;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskMonitoringTabbedPane = new javax.swing.JTabbedPane();
        taskQueuePanel = new javax.swing.JPanel();
        taskQueueScrollPane = new javax.swing.JScrollPane();
        taskQueueTable = new javax.swing.JTable();
        deleteDbTaskButton = new javax.swing.JButton();
        completedTaskQueuePanel = new javax.swing.JPanel();
        completedTaskQueueScrollPane = new javax.swing.JScrollPane();
        completedTaskQueueTable = new javax.swing.JTable();
        deleteCompletedTaskButton = new javax.swing.JButton();
        purgeCompletedTasksButton = new javax.swing.JButton();
        taskErrorQueuePanel = new javax.swing.JPanel();
        taskErrorQueueScrollPane = new javax.swing.JScrollPane();
        taskErrorQueueTable = new javax.swing.JTable();
        errorDetailLabel = new javax.swing.JLabel();
        errorDetailTextAreaScrollPane = new javax.swing.JScrollPane();
        errorDetailTextArea = new javax.swing.JTextArea();
        deleteTaskErrorButton = new javax.swing.JButton();
        resendTaskErrorButton = new javax.swing.JButton();
        purgeTaskErrorsButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Task monitoring");

        taskQueuePanel.setBackground(java.awt.Color.white);

        taskQueueScrollPane.setOpaque(false);

        taskQueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taskQueueTable.setOpaque(false);
        taskQueueScrollPane.setViewportView(taskQueueTable);

        deleteDbTaskButton.setText("delete");
        deleteDbTaskButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteDbTaskButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteDbTaskButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout taskQueuePanelLayout = new javax.swing.GroupLayout(taskQueuePanel);
        taskQueuePanel.setLayout(taskQueuePanelLayout);
        taskQueuePanelLayout.setHorizontalGroup(
            taskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskQueuePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteDbTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        taskQueuePanelLayout.setVerticalGroup(
            taskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteDbTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        taskMonitoringTabbedPane.addTab("Tasks", taskQueuePanel);

        completedTaskQueuePanel.setBackground(java.awt.Color.white);

        completedTaskQueueScrollPane.setOpaque(false);

        completedTaskQueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        completedTaskQueueTable.setToolTipText("");
        completedTaskQueueTable.setOpaque(false);
        completedTaskQueueScrollPane.setViewportView(completedTaskQueueTable);

        deleteCompletedTaskButton.setText("delete");
        deleteCompletedTaskButton.setToolTipText("remove the selected storage error");
        deleteCompletedTaskButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteCompletedTaskButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteCompletedTaskButton.setPreferredSize(new java.awt.Dimension(80, 25));

        purgeCompletedTasksButton.setText("purge");
        purgeCompletedTasksButton.setToolTipText("remove all messages (irreversable!)");
        purgeCompletedTasksButton.setMaximumSize(new java.awt.Dimension(80, 25));
        purgeCompletedTasksButton.setMinimumSize(new java.awt.Dimension(80, 25));
        purgeCompletedTasksButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout completedTaskQueuePanelLayout = new javax.swing.GroupLayout(completedTaskQueuePanel);
        completedTaskQueuePanel.setLayout(completedTaskQueuePanelLayout);
        completedTaskQueuePanelLayout.setHorizontalGroup(
            completedTaskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedTaskQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(completedTaskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(completedTaskQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, completedTaskQueuePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteCompletedTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purgeCompletedTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        completedTaskQueuePanelLayout.setVerticalGroup(
            completedTaskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedTaskQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(completedTaskQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(completedTaskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCompletedTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purgeCompletedTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        taskMonitoringTabbedPane.addTab("Completed tasks", completedTaskQueuePanel);

        taskErrorQueuePanel.setBackground(java.awt.Color.white);

        taskErrorQueueScrollPane.setOpaque(false);

        taskErrorQueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taskErrorQueueTable.setToolTipText("select a row to see the error details");
        taskErrorQueueTable.setOpaque(false);
        taskErrorQueueScrollPane.setViewportView(taskErrorQueueTable);

        errorDetailLabel.setText("Error detail");

        errorDetailTextArea.setEditable(false);
        errorDetailTextArea.setColumns(20);
        errorDetailTextArea.setLineWrap(true);
        errorDetailTextArea.setRows(5);
        errorDetailTextArea.setWrapStyleWord(true);
        errorDetailTextAreaScrollPane.setViewportView(errorDetailTextArea);

        deleteTaskErrorButton.setText("delete");
        deleteTaskErrorButton.setToolTipText("remove the selected storage error");
        deleteTaskErrorButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteTaskErrorButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteTaskErrorButton.setPreferredSize(new java.awt.Dimension(80, 25));

        resendTaskErrorButton.setText("resend");
        resendTaskErrorButton.setToolTipText("resend the storage error as a storage task");
        resendTaskErrorButton.setMaximumSize(new java.awt.Dimension(80, 25));
        resendTaskErrorButton.setMinimumSize(new java.awt.Dimension(80, 25));
        resendTaskErrorButton.setPreferredSize(new java.awt.Dimension(80, 25));

        purgeTaskErrorsButton.setText("purge");
        purgeTaskErrorsButton.setToolTipText("remove all messages (irreversable!)");
        purgeTaskErrorsButton.setMaximumSize(new java.awt.Dimension(80, 25));
        purgeTaskErrorsButton.setMinimumSize(new java.awt.Dimension(80, 25));
        purgeTaskErrorsButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout taskErrorQueuePanelLayout = new javax.swing.GroupLayout(taskErrorQueuePanel);
        taskErrorQueuePanel.setLayout(taskErrorQueuePanelLayout);
        taskErrorQueuePanelLayout.setHorizontalGroup(
            taskErrorQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskErrorQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskErrorQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskErrorQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addGroup(taskErrorQueuePanelLayout.createSequentialGroup()
                        .addComponent(errorDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(errorDetailTextAreaScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskErrorQueuePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(resendTaskErrorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteTaskErrorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purgeTaskErrorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        taskErrorQueuePanelLayout.setVerticalGroup(
            taskErrorQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskErrorQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskErrorQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorDetailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorDetailTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taskErrorQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTaskErrorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resendTaskErrorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purgeTaskErrorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        taskMonitoringTabbedPane.addTab("Task Errors", taskErrorQueuePanel);

        cancelButton.setText("cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(80, 25));
        cancelButton.setMinimumSize(new java.awt.Dimension(80, 25));
        cancelButton.setPreferredSize(new java.awt.Dimension(80, 25));

        refreshButton.setText("refresh");
        refreshButton.setMaximumSize(new java.awt.Dimension(80, 25));
        refreshButton.setMinimumSize(new java.awt.Dimension(80, 25));
        refreshButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskMonitoringTabbedPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(taskMonitoringTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel completedTaskQueuePanel;
    private javax.swing.JScrollPane completedTaskQueueScrollPane;
    private javax.swing.JTable completedTaskQueueTable;
    private javax.swing.JButton deleteCompletedTaskButton;
    private javax.swing.JButton deleteDbTaskButton;
    private javax.swing.JButton deleteTaskErrorButton;
    private javax.swing.JLabel errorDetailLabel;
    private javax.swing.JTextArea errorDetailTextArea;
    private javax.swing.JScrollPane errorDetailTextAreaScrollPane;
    private javax.swing.JButton purgeCompletedTasksButton;
    private javax.swing.JButton purgeTaskErrorsButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton resendTaskErrorButton;
    private javax.swing.JPanel taskErrorQueuePanel;
    private javax.swing.JScrollPane taskErrorQueueScrollPane;
    private javax.swing.JTable taskErrorQueueTable;
    private javax.swing.JTabbedPane taskMonitoringTabbedPane;
    private javax.swing.JPanel taskQueuePanel;
    private javax.swing.JScrollPane taskQueueScrollPane;
    private javax.swing.JTable taskQueueTable;
    // End of variables declaration//GEN-END:variables
}
