/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.colims.client.view;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author Niels Hulstaert
 */
public class TaskManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaskMonitoringPanel
     */
    public TaskManagementPanel() {
        initComponents();

        taskQueueScrollPane.getViewport().setOpaque(false);
        taskQueueTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        taskErrorQueueScrollPane.getViewport().setOpaque(false);
        taskErrorQueueTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        completedTaskQueueScrollPane.getViewport().setOpaque(false);
        completedTaskQueueTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    public JTable getCompletedTaskQueueTable() {
        return completedTaskQueueTable;
    }

    public JButton getDeleteCompletedTaskButton() {
        return deleteCompletedTaskButton;
    }

    public JButton getDeleteDbTaskButton() {
        return deleteDbTaskButton;
    }

    public JButton getDeleteTaskErrorButton() {
        return deleteTaskErrorButton;
    }

    public JTextArea getErrorDetailTextArea() {
        return errorDetailTextArea;
    }

    public JTextArea getNotificationTextArea() {
        return notificationTextArea;
    }

    public JButton getPurgeCompletedTasksButton() {
        return purgeCompletedTasksButton;
    }

    public JButton getPurgeTaskErrorsButton() {
        return purgeTaskErrorsButton;
    }

    public JButton getResendTaskErrorButton() {
        return resendTaskErrorButton;
    }

    public JTable getTaskErrorQueueTable() {
        return taskErrorQueueTable;
    }

    public JTable getTaskQueueTable() {
        return taskQueueTable;
    }  

    public JButton getClearNotificationsButton() {
        return clearNotificationsButton;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        notificationPanel = new javax.swing.JPanel();
        notificationScrollPanel = new javax.swing.JScrollPane();
        notificationTextArea = new javax.swing.JTextArea();
        clearNotificationsButton = new javax.swing.JButton();
        taskQueuePanel = new javax.swing.JPanel();
        taskQueueScrollPane = new javax.swing.JScrollPane();
        taskQueueTable = new javax.swing.JTable();
        deleteDbTaskButton = new javax.swing.JButton();
        completedTaskQueuePanel = new javax.swing.JPanel();
        completedTaskQueueScrollPane = new javax.swing.JScrollPane();
        completedTaskQueueTable = new javax.swing.JTable();
        deleteCompletedTaskButton = new javax.swing.JButton();
        purgeCompletedTasksButton = new javax.swing.JButton();
        taskErrorQueuePanel = new javax.swing.JPanel();
        taskErrorQueueScrollPane = new javax.swing.JScrollPane();
        taskErrorQueueTable = new javax.swing.JTable();
        errorDetailLabel = new javax.swing.JLabel();
        errorDetailTextAreaScrollPane = new javax.swing.JScrollPane();
        errorDetailTextArea = new javax.swing.JTextArea();
        deleteTaskErrorButton = new javax.swing.JButton();
        resendTaskErrorButton = new javax.swing.JButton();
        purgeTaskErrorsButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        notificationPanel.setBackground(new java.awt.Color(255, 255, 255));
        notificationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Activity"));

        notificationTextArea.setEditable(false);
        notificationTextArea.setColumns(20);
        notificationTextArea.setRows(5);
        notificationTextArea.setText("...");
        notificationScrollPanel.setViewportView(notificationTextArea);

        clearNotificationsButton.setText("clear");
        clearNotificationsButton.setMaximumSize(new java.awt.Dimension(80, 25));
        clearNotificationsButton.setMinimumSize(new java.awt.Dimension(80, 25));
        clearNotificationsButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout notificationPanelLayout = new javax.swing.GroupLayout(notificationPanel);
        notificationPanel.setLayout(notificationPanelLayout);
        notificationPanelLayout.setHorizontalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificationPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clearNotificationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(notificationScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE))
                .addContainerGap())
        );
        notificationPanelLayout.setVerticalGroup(
            notificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notificationScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearNotificationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(notificationPanel, gridBagConstraints);

        taskQueuePanel.setBackground(java.awt.Color.white);
        taskQueuePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pending"));

        taskQueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taskQueueTable.setOpaque(false);
        taskQueueScrollPane.setViewportView(taskQueueTable);

        deleteDbTaskButton.setText("delete");
        deleteDbTaskButton.setToolTipText("remove the selected task (irreversable!)");
        deleteDbTaskButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteDbTaskButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteDbTaskButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout taskQueuePanelLayout = new javax.swing.GroupLayout(taskQueuePanel);
        taskQueuePanel.setLayout(taskQueuePanelLayout);
        taskQueuePanelLayout.setHorizontalGroup(
            taskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskQueuePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteDbTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        taskQueuePanelLayout.setVerticalGroup(
            taskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteDbTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(taskQueuePanel, gridBagConstraints);

        completedTaskQueuePanel.setBackground(java.awt.Color.white);
        completedTaskQueuePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Completed"));

        completedTaskQueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        completedTaskQueueTable.setToolTipText("");
        completedTaskQueueTable.setOpaque(false);
        completedTaskQueueScrollPane.setViewportView(completedTaskQueueTable);

        deleteCompletedTaskButton.setText("delete");
        deleteCompletedTaskButton.setToolTipText("remove the selected completed task");
        deleteCompletedTaskButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteCompletedTaskButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteCompletedTaskButton.setPreferredSize(new java.awt.Dimension(80, 25));

        purgeCompletedTasksButton.setText("purge");
        purgeCompletedTasksButton.setToolTipText("remove all completed tasks");
        purgeCompletedTasksButton.setMaximumSize(new java.awt.Dimension(80, 25));
        purgeCompletedTasksButton.setMinimumSize(new java.awt.Dimension(80, 25));
        purgeCompletedTasksButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout completedTaskQueuePanelLayout = new javax.swing.GroupLayout(completedTaskQueuePanel);
        completedTaskQueuePanel.setLayout(completedTaskQueuePanelLayout);
        completedTaskQueuePanelLayout.setHorizontalGroup(
            completedTaskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedTaskQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(completedTaskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(completedTaskQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, completedTaskQueuePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteCompletedTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purgeCompletedTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        completedTaskQueuePanelLayout.setVerticalGroup(
            completedTaskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedTaskQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(completedTaskQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(completedTaskQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCompletedTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purgeCompletedTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(completedTaskQueuePanel, gridBagConstraints);

        taskErrorQueuePanel.setBackground(java.awt.Color.white);
        taskErrorQueuePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Errors"));

        taskErrorQueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taskErrorQueueTable.setToolTipText("select a row to see the error details");
        taskErrorQueueTable.setOpaque(false);
        taskErrorQueueScrollPane.setViewportView(taskErrorQueueTable);

        errorDetailLabel.setText("Error detail");

        errorDetailTextArea.setEditable(false);
        errorDetailTextArea.setColumns(20);
        errorDetailTextArea.setLineWrap(true);
        errorDetailTextArea.setRows(5);
        errorDetailTextArea.setWrapStyleWord(true);
        errorDetailTextAreaScrollPane.setViewportView(errorDetailTextArea);

        deleteTaskErrorButton.setText("delete");
        deleteTaskErrorButton.setToolTipText("remove the selected task error");
        deleteTaskErrorButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteTaskErrorButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteTaskErrorButton.setPreferredSize(new java.awt.Dimension(80, 25));

        resendTaskErrorButton.setText("resend");
        resendTaskErrorButton.setToolTipText("resend the storage error as a storage task");
        resendTaskErrorButton.setMaximumSize(new java.awt.Dimension(80, 25));
        resendTaskErrorButton.setMinimumSize(new java.awt.Dimension(80, 25));
        resendTaskErrorButton.setPreferredSize(new java.awt.Dimension(80, 25));

        purgeTaskErrorsButton.setText("purge");
        purgeTaskErrorsButton.setToolTipText("remove all taks errors");
        purgeTaskErrorsButton.setMaximumSize(new java.awt.Dimension(80, 25));
        purgeTaskErrorsButton.setMinimumSize(new java.awt.Dimension(80, 25));
        purgeTaskErrorsButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout taskErrorQueuePanelLayout = new javax.swing.GroupLayout(taskErrorQueuePanel);
        taskErrorQueuePanel.setLayout(taskErrorQueuePanelLayout);
        taskErrorQueuePanelLayout.setHorizontalGroup(
            taskErrorQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskErrorQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskErrorQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskErrorQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addGroup(taskErrorQueuePanelLayout.createSequentialGroup()
                        .addComponent(errorDetailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(errorDetailTextAreaScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskErrorQueuePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(resendTaskErrorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteTaskErrorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purgeTaskErrorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        taskErrorQueuePanelLayout.setVerticalGroup(
            taskErrorQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskErrorQueuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskErrorQueueScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorDetailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorDetailTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taskErrorQueuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTaskErrorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resendTaskErrorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purgeTaskErrorsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(taskErrorQueuePanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearNotificationsButton;
    private javax.swing.JPanel completedTaskQueuePanel;
    private javax.swing.JScrollPane completedTaskQueueScrollPane;
    private javax.swing.JTable completedTaskQueueTable;
    private javax.swing.JButton deleteCompletedTaskButton;
    private javax.swing.JButton deleteDbTaskButton;
    private javax.swing.JButton deleteTaskErrorButton;
    private javax.swing.JLabel errorDetailLabel;
    private javax.swing.JTextArea errorDetailTextArea;
    private javax.swing.JScrollPane errorDetailTextAreaScrollPane;
    private javax.swing.JPanel notificationPanel;
    private javax.swing.JScrollPane notificationScrollPanel;
    private javax.swing.JTextArea notificationTextArea;
    private javax.swing.JButton purgeCompletedTasksButton;
    private javax.swing.JButton purgeTaskErrorsButton;
    private javax.swing.JButton resendTaskErrorButton;
    private javax.swing.JPanel taskErrorQueuePanel;
    private javax.swing.JScrollPane taskErrorQueueScrollPane;
    private javax.swing.JTable taskErrorQueueTable;
    private javax.swing.JPanel taskQueuePanel;
    private javax.swing.JScrollPane taskQueueScrollPane;
    private javax.swing.JTable taskQueueTable;
    // End of variables declaration//GEN-END:variables
}
