package com.compomics.colims.client.view;

import java.awt.Color;
import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author niels
 */
public class UserManagementDialog extends javax.swing.JDialog {

    /**
     * Creates new form UserManagementDialog
     */
    public UserManagementDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        setLocationRelativeTo(parent);
    }

    public JButton getAddUserButton() {
        return addUserButton;
    }

    public JButton getDeleteUserButton() {
        return deleteUserButton;
    }

    public JTextField getEmailTextField() {
        return emailTextField;
    }

    public JTextField getFirstNameTextField() {
        return firstNameTextField;
    }

    public JTextField getLastNameTextField() {
        return lastNameTextField;
    }

    public JPasswordField getPasswordTextField() {
        return passwordTextField;
    }

    public JComboBox getRoleComboBox() {
        return groupComboBox;
    }

    public JButton getSaveOrUpdateButton() {
        return saveOrUpdateButton;
    }

    public JList getUserList() {
        return userList;
    }

    public JTextField getUserNameTextField() {
        return userNameTextField;
    }

    public JLabel getUserStateInfoLabel() {
        return userStateInfoLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userManagementTabbedPane = new javax.swing.JTabbedPane();
        userCrudPanel = new javax.swing.JPanel();
        userOverviewPanel = new javax.swing.JPanel();
        userListScrollPane = new javax.swing.JScrollPane();
        userList = new javax.swing.JList();
        addUserButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        userDetailPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        groupComboBox = new javax.swing.JComboBox();
        passwordTextField = new javax.swing.JPasswordField();
        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        saveOrUpdateButton = new javax.swing.JButton();
        userStateInfoLabel = new javax.swing.JLabel();
        groupCrudPanel = new javax.swing.JPanel();
        groupOverviewPanel = new javax.swing.JPanel();
        groupListScrollPane = new javax.swing.JScrollPane();
        userList1 = new javax.swing.JList();
        addGroupButton = new javax.swing.JButton();
        deleteGroupButton = new javax.swing.JButton();
        groupDetailPanel = new javax.swing.JPanel();
        firstNameLabel1 = new javax.swing.JLabel();
        lastNameLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        groupLabel1 = new javax.swing.JLabel();
        firstNameTextField1 = new javax.swing.JTextField();
        lastNameTextField1 = new javax.swing.JTextField();
        emailTextField1 = new javax.swing.JTextField();
        groupComboBox1 = new javax.swing.JComboBox();
        passwordTextField1 = new javax.swing.JPasswordField();
        userNameLabel1 = new javax.swing.JLabel();
        userNameTextField1 = new javax.swing.JTextField();
        saveOrUpdateButton1 = new javax.swing.JButton();
        userStateInfoLabel1 = new javax.swing.JLabel();
        roleCrudPanel = new javax.swing.JPanel();
        roleOverviewPanel = new javax.swing.JPanel();
        roleListScrollPane = new javax.swing.JScrollPane();
        userList2 = new javax.swing.JList();
        addRoleButton = new javax.swing.JButton();
        deleteRoleButton = new javax.swing.JButton();
        roleDetailPanel = new javax.swing.JPanel();
        firstNameLabel2 = new javax.swing.JLabel();
        lastNameLabel2 = new javax.swing.JLabel();
        emailLabel2 = new javax.swing.JLabel();
        passwordLabel2 = new javax.swing.JLabel();
        groupLabel2 = new javax.swing.JLabel();
        firstNameTextField2 = new javax.swing.JTextField();
        lastNameTextField2 = new javax.swing.JTextField();
        emailTextField2 = new javax.swing.JTextField();
        groupComboBox2 = new javax.swing.JComboBox();
        passwordTextField2 = new javax.swing.JPasswordField();
        userNameLabel2 = new javax.swing.JLabel();
        userNameTextField2 = new javax.swing.JTextField();
        saveOrUpdateButton2 = new javax.swing.JButton();
        userStateInfoLabel2 = new javax.swing.JLabel();
        permissionCrudPanel = new javax.swing.JPanel();
        permissionOverviewPanel = new javax.swing.JPanel();
        permissionListScrollPane = new javax.swing.JScrollPane();
        userList3 = new javax.swing.JList();
        addPermissionButton = new javax.swing.JButton();
        deletePermissionButton = new javax.swing.JButton();
        permissionDetailPanel = new javax.swing.JPanel();
        firstNameLabel3 = new javax.swing.JLabel();
        lastNameLabel3 = new javax.swing.JLabel();
        emailLabel3 = new javax.swing.JLabel();
        passwordLabel3 = new javax.swing.JLabel();
        groupLabel3 = new javax.swing.JLabel();
        firstNameTextField3 = new javax.swing.JTextField();
        lastNameTextField3 = new javax.swing.JTextField();
        emailTextField3 = new javax.swing.JTextField();
        groupComboBox3 = new javax.swing.JComboBox();
        passwordTextField3 = new javax.swing.JPasswordField();
        userNameLabel3 = new javax.swing.JLabel();
        userNameTextField3 = new javax.swing.JTextField();
        saveOrUpdateButton3 = new javax.swing.JButton();
        userStateInfoLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        userOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Overview"));
        userOverviewPanel.setOpaque(false);
        userOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        userListScrollPane.setViewportView(userList);

        addUserButton.setText("add");
        addUserButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addUserButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addUserButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deleteUserButton.setText("delete");
        deleteUserButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteUserButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteUserButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout userOverviewPanelLayout = new javax.swing.GroupLayout(userOverviewPanel);
        userOverviewPanel.setLayout(userOverviewPanelLayout);
        userOverviewPanelLayout.setHorizontalGroup(
            userOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(userOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteUserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        userOverviewPanelLayout.setVerticalGroup(
            userOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap())
        );

        userDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));
        userDetailPanel.setOpaque(false);
        userDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        firstNameLabel.setText("first name");

        lastNameLabel.setText("last name");

        emailLabel.setText("email");

        passwordLabel.setText("password");

        groupLabel.setText("group");

        userNameLabel.setText("user name");
        userNameLabel.setPreferredSize(new java.awt.Dimension(48, 14));

        saveOrUpdateButton.setText("save");
        saveOrUpdateButton.setMaximumSize(new java.awt.Dimension(80, 25));
        saveOrUpdateButton.setMinimumSize(new java.awt.Dimension(80, 25));
        saveOrUpdateButton.setPreferredSize(new java.awt.Dimension(80, 25));

        userStateInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userStateInfoLabel.setForeground(new java.awt.Color(255, 0, 0));
        userStateInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        userStateInfoLabel.setMaximumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel.setMinimumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout userDetailPanelLayout = new javax.swing.GroupLayout(userDetailPanel);
        userDetailPanel.setLayout(userDetailPanelLayout);
        userDetailPanelLayout.setHorizontalGroup(
            userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userDetailPanelLayout.createSequentialGroup()
                        .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(groupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userNameTextField)
                            .addComponent(firstNameTextField)
                            .addComponent(lastNameTextField)
                            .addComponent(emailTextField)
                            .addComponent(passwordTextField)
                            .addComponent(groupComboBox, 0, 267, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        userDetailPanelLayout.setVerticalGroup(
            userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailPanelLayout.createSequentialGroup()
                .addComponent(userStateInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupLabel)
                    .addComponent(groupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveOrUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout userCrudPanelLayout = new javax.swing.GroupLayout(userCrudPanel);
        userCrudPanel.setLayout(userCrudPanelLayout);
        userCrudPanelLayout.setHorizontalGroup(
            userCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userOverviewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addComponent(userDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );
        userCrudPanelLayout.setVerticalGroup(
            userCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userCrudPanelLayout.createSequentialGroup()
                .addComponent(userOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userManagementTabbedPane.addTab("Users", userCrudPanel);

        groupOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Overview"));
        groupOverviewPanel.setOpaque(false);
        groupOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        groupListScrollPane.setViewportView(userList1);

        addGroupButton.setText("add");
        addGroupButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addGroupButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addGroupButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deleteGroupButton.setText("delete");
        deleteGroupButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteGroupButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteGroupButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout groupOverviewPanelLayout = new javax.swing.GroupLayout(groupOverviewPanel);
        groupOverviewPanel.setLayout(groupOverviewPanelLayout);
        groupOverviewPanelLayout.setHorizontalGroup(
            groupOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(groupOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteGroupButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addGroupButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        groupOverviewPanelLayout.setVerticalGroup(
            groupOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groupOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(groupListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap())
        );

        groupDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));
        groupDetailPanel.setOpaque(false);
        groupDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        firstNameLabel1.setText("first name");

        lastNameLabel1.setText("last name");

        emailLabel1.setText("email");

        passwordLabel1.setText("password");

        groupLabel1.setText("group");

        userNameLabel1.setText("user name");
        userNameLabel1.setPreferredSize(new java.awt.Dimension(48, 14));

        saveOrUpdateButton1.setText("save");
        saveOrUpdateButton1.setMaximumSize(new java.awt.Dimension(80, 25));
        saveOrUpdateButton1.setMinimumSize(new java.awt.Dimension(80, 25));
        saveOrUpdateButton1.setPreferredSize(new java.awt.Dimension(80, 25));

        userStateInfoLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userStateInfoLabel1.setForeground(new java.awt.Color(255, 0, 0));
        userStateInfoLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        userStateInfoLabel1.setMaximumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel1.setMinimumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel1.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout groupDetailPanelLayout = new javax.swing.GroupLayout(groupDetailPanel);
        groupDetailPanel.setLayout(groupDetailPanelLayout);
        groupDetailPanelLayout.setHorizontalGroup(
            groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveOrUpdateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(groupDetailPanelLayout.createSequentialGroup()
                        .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(groupLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userNameTextField1)
                            .addComponent(firstNameTextField1)
                            .addComponent(lastNameTextField1)
                            .addComponent(emailTextField1)
                            .addComponent(passwordTextField1)
                            .addComponent(groupComboBox1, 0, 267, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userStateInfoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        groupDetailPanelLayout.setVerticalGroup(
            groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupDetailPanelLayout.createSequentialGroup()
                .addComponent(userStateInfoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel1)
                    .addComponent(firstNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel1)
                    .addComponent(lastNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel1)
                    .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel1)
                    .addComponent(passwordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(groupDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupLabel1)
                    .addComponent(groupComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveOrUpdateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout groupCrudPanelLayout = new javax.swing.GroupLayout(groupCrudPanel);
        groupCrudPanel.setLayout(groupCrudPanelLayout);
        groupCrudPanelLayout.setHorizontalGroup(
            groupCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupOverviewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addComponent(groupDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
        groupCrudPanelLayout.setVerticalGroup(
            groupCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupCrudPanelLayout.createSequentialGroup()
                .addComponent(groupOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userManagementTabbedPane.addTab("Users", groupCrudPanel);

        roleOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Overview"));
        roleOverviewPanel.setOpaque(false);
        roleOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        roleListScrollPane.setViewportView(userList2);

        addRoleButton.setText("add");
        addRoleButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addRoleButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addRoleButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deleteRoleButton.setText("delete");
        deleteRoleButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deleteRoleButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deleteRoleButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout roleOverviewPanelLayout = new javax.swing.GroupLayout(roleOverviewPanel);
        roleOverviewPanel.setLayout(roleOverviewPanelLayout);
        roleOverviewPanelLayout.setHorizontalGroup(
            roleOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roleListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(roleOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteRoleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRoleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        roleOverviewPanelLayout.setVerticalGroup(
            roleOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roleOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roleOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addRoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteRoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(roleListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap())
        );

        roleDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));
        roleDetailPanel.setOpaque(false);
        roleDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        firstNameLabel2.setText("first name");

        lastNameLabel2.setText("last name");

        emailLabel2.setText("email");

        passwordLabel2.setText("password");

        groupLabel2.setText("group");

        userNameLabel2.setText("user name");
        userNameLabel2.setPreferredSize(new java.awt.Dimension(48, 14));

        saveOrUpdateButton2.setText("save");
        saveOrUpdateButton2.setMaximumSize(new java.awt.Dimension(80, 25));
        saveOrUpdateButton2.setMinimumSize(new java.awt.Dimension(80, 25));
        saveOrUpdateButton2.setPreferredSize(new java.awt.Dimension(80, 25));

        userStateInfoLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userStateInfoLabel2.setForeground(new java.awt.Color(255, 0, 0));
        userStateInfoLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        userStateInfoLabel2.setMaximumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel2.setMinimumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel2.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout roleDetailPanelLayout = new javax.swing.GroupLayout(roleDetailPanel);
        roleDetailPanel.setLayout(roleDetailPanelLayout);
        roleDetailPanelLayout.setHorizontalGroup(
            roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveOrUpdateButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roleDetailPanelLayout.createSequentialGroup()
                        .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(groupLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userNameTextField2)
                            .addComponent(firstNameTextField2)
                            .addComponent(lastNameTextField2)
                            .addComponent(emailTextField2)
                            .addComponent(passwordTextField2)
                            .addComponent(groupComboBox2, 0, 267, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roleDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userStateInfoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roleDetailPanelLayout.setVerticalGroup(
            roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roleDetailPanelLayout.createSequentialGroup()
                .addComponent(userStateInfoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel2)
                    .addComponent(firstNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel2)
                    .addComponent(lastNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel2)
                    .addComponent(emailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel2)
                    .addComponent(passwordTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roleDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupLabel2)
                    .addComponent(groupComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveOrUpdateButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout roleCrudPanelLayout = new javax.swing.GroupLayout(roleCrudPanel);
        roleCrudPanel.setLayout(roleCrudPanelLayout);
        roleCrudPanelLayout.setHorizontalGroup(
            roleCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roleOverviewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addComponent(roleDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
        roleCrudPanelLayout.setVerticalGroup(
            roleCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roleCrudPanelLayout.createSequentialGroup()
                .addComponent(roleOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userManagementTabbedPane.addTab("Users", roleCrudPanel);

        permissionOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Overview"));
        permissionOverviewPanel.setOpaque(false);
        permissionOverviewPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        permissionListScrollPane.setViewportView(userList3);

        addPermissionButton.setText("add");
        addPermissionButton.setMaximumSize(new java.awt.Dimension(80, 25));
        addPermissionButton.setMinimumSize(new java.awt.Dimension(80, 25));
        addPermissionButton.setPreferredSize(new java.awt.Dimension(80, 25));

        deletePermissionButton.setText("delete");
        deletePermissionButton.setMaximumSize(new java.awt.Dimension(80, 25));
        deletePermissionButton.setMinimumSize(new java.awt.Dimension(80, 25));
        deletePermissionButton.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout permissionOverviewPanelLayout = new javax.swing.GroupLayout(permissionOverviewPanel);
        permissionOverviewPanel.setLayout(permissionOverviewPanelLayout);
        permissionOverviewPanelLayout.setHorizontalGroup(
            permissionOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(permissionListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(permissionOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletePermissionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPermissionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        permissionOverviewPanelLayout.setVerticalGroup(
            permissionOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permissionOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(permissionOverviewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addPermissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletePermissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(permissionListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap())
        );

        permissionDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));
        permissionDetailPanel.setOpaque(false);
        permissionDetailPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        firstNameLabel3.setText("first name");

        lastNameLabel3.setText("last name");

        emailLabel3.setText("email");

        passwordLabel3.setText("password");

        groupLabel3.setText("group");

        userNameLabel3.setText("user name");
        userNameLabel3.setPreferredSize(new java.awt.Dimension(48, 14));

        saveOrUpdateButton3.setText("save");
        saveOrUpdateButton3.setMaximumSize(new java.awt.Dimension(80, 25));
        saveOrUpdateButton3.setMinimumSize(new java.awt.Dimension(80, 25));
        saveOrUpdateButton3.setPreferredSize(new java.awt.Dimension(80, 25));

        userStateInfoLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userStateInfoLabel3.setForeground(new java.awt.Color(255, 0, 0));
        userStateInfoLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        userStateInfoLabel3.setMaximumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel3.setMinimumSize(new java.awt.Dimension(100, 20));
        userStateInfoLabel3.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout permissionDetailPanelLayout = new javax.swing.GroupLayout(permissionDetailPanel);
        permissionDetailPanel.setLayout(permissionDetailPanelLayout);
        permissionDetailPanelLayout.setHorizontalGroup(
            permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveOrUpdateButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(permissionDetailPanelLayout.createSequentialGroup()
                        .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(groupLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userNameTextField3)
                            .addComponent(firstNameTextField3)
                            .addComponent(lastNameTextField3)
                            .addComponent(emailTextField3)
                            .addComponent(passwordTextField3)
                            .addComponent(groupComboBox3, 0, 267, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, permissionDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userStateInfoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        permissionDetailPanelLayout.setVerticalGroup(
            permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permissionDetailPanelLayout.createSequentialGroup()
                .addComponent(userStateInfoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel3)
                    .addComponent(firstNameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel3)
                    .addComponent(lastNameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel3)
                    .addComponent(emailTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel3)
                    .addComponent(passwordTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(permissionDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupLabel3)
                    .addComponent(groupComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveOrUpdateButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout permissionCrudPanelLayout = new javax.swing.GroupLayout(permissionCrudPanel);
        permissionCrudPanel.setLayout(permissionCrudPanelLayout);
        permissionCrudPanelLayout.setHorizontalGroup(
            permissionCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(permissionOverviewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addComponent(permissionDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
        permissionCrudPanelLayout.setVerticalGroup(
            permissionCrudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, permissionCrudPanelLayout.createSequentialGroup()
                .addComponent(permissionOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permissionDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userManagementTabbedPane.addTab("Users", permissionCrudPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userManagementTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userManagementTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroupButton;
    private javax.swing.JButton addPermissionButton;
    private javax.swing.JButton addRoleButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton deleteGroupButton;
    private javax.swing.JButton deletePermissionButton;
    private javax.swing.JButton deleteRoleButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JLabel emailLabel3;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JTextField emailTextField2;
    private javax.swing.JTextField emailTextField3;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLabel1;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JLabel firstNameLabel3;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField firstNameTextField1;
    private javax.swing.JTextField firstNameTextField2;
    private javax.swing.JTextField firstNameTextField3;
    private javax.swing.JComboBox groupComboBox;
    private javax.swing.JComboBox groupComboBox1;
    private javax.swing.JComboBox groupComboBox2;
    private javax.swing.JComboBox groupComboBox3;
    private javax.swing.JPanel groupCrudPanel;
    private javax.swing.JPanel groupDetailPanel;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JLabel groupLabel1;
    private javax.swing.JLabel groupLabel2;
    private javax.swing.JLabel groupLabel3;
    private javax.swing.JScrollPane groupListScrollPane;
    private javax.swing.JPanel groupOverviewPanel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameLabel1;
    private javax.swing.JLabel lastNameLabel2;
    private javax.swing.JLabel lastNameLabel3;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField lastNameTextField1;
    private javax.swing.JTextField lastNameTextField2;
    private javax.swing.JTextField lastNameTextField3;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JLabel passwordLabel2;
    private javax.swing.JLabel passwordLabel3;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPasswordField passwordTextField1;
    private javax.swing.JPasswordField passwordTextField2;
    private javax.swing.JPasswordField passwordTextField3;
    private javax.swing.JPanel permissionCrudPanel;
    private javax.swing.JPanel permissionDetailPanel;
    private javax.swing.JScrollPane permissionListScrollPane;
    private javax.swing.JPanel permissionOverviewPanel;
    private javax.swing.JPanel roleCrudPanel;
    private javax.swing.JPanel roleDetailPanel;
    private javax.swing.JScrollPane roleListScrollPane;
    private javax.swing.JPanel roleOverviewPanel;
    private javax.swing.JButton saveOrUpdateButton;
    private javax.swing.JButton saveOrUpdateButton1;
    private javax.swing.JButton saveOrUpdateButton2;
    private javax.swing.JButton saveOrUpdateButton3;
    private javax.swing.JPanel userCrudPanel;
    private javax.swing.JPanel userDetailPanel;
    private javax.swing.JList userList;
    private javax.swing.JList userList1;
    private javax.swing.JList userList2;
    private javax.swing.JList userList3;
    private javax.swing.JScrollPane userListScrollPane;
    private javax.swing.JTabbedPane userManagementTabbedPane;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userNameLabel1;
    private javax.swing.JLabel userNameLabel2;
    private javax.swing.JLabel userNameLabel3;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JTextField userNameTextField1;
    private javax.swing.JTextField userNameTextField2;
    private javax.swing.JTextField userNameTextField3;
    private javax.swing.JPanel userOverviewPanel;
    private javax.swing.JLabel userStateInfoLabel;
    private javax.swing.JLabel userStateInfoLabel1;
    private javax.swing.JLabel userStateInfoLabel2;
    private javax.swing.JLabel userStateInfoLabel3;
    // End of variables declaration//GEN-END:variables
}
